// Browser contracts only: no real site, downloader, cookie, or background service.
const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../automations.js'),'utf8');
const durable=new Map();
let failStorage=false;
const tick=()=>new Promise(setImmediate);
async function browser({username='alice',origin='http://nas.local:7120',handler=async()=>({})}={}){
  const elements=new Map(),calls=[],timers=new Map();let serial=0;
  const element=selector=>{if(!elements.has(selector))elements.set(selector,{hidden:false,value:'',innerHTML:'',textContent:'',disabled:false,open:false,dataset:{},children:[],elements:{},classList:{toggle(){}},setAttribute(k,v){this[k]=v;},addEventListener(){},querySelectorAll(){return [];},focus(){},showModal(){this.open=true;},close(){this.open=false;},querySelector(){return element('button');}});return elements.get(selector);};
  const context=vm.createContext({console,crypto:require('node:crypto').webcrypto,TextEncoder,location:{origin},document:{querySelector:element},$:element,esc:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),date:v=>v?'date '+v:'—',uuid:()=>require('node:crypto').randomUUID(),toast:message=>element('#toast').textContent=message,resourceView(){},localStorage:{getItem:k=>durable.get(k)||null,setItem(k,v){if(failStorage)throw Error('storage');durable.set(k,v);}},FormData:class{constructor(form){this.entries=Object.entries(form.values);} [Symbol.iterator](){return this.entries[Symbol.iterator]();}},setTimeout(fn,ms){const id=++serial;timers.set(id,{fn,ms});return id;},clearTimeout(id){timers.delete(id);},api:async(p,m='GET',body)=>{calls.push({p,m,body});if(p==='/me')return {username};return handler(p,m,body);}});
  const run=code=>vm.runInContext(code,context);vm.runInContext(source,context);await run('initializeAutomations()');run('automationState.active=true');
  return {run,element,calls,timers,context};
}
function json(value){return JSON.parse(JSON.stringify(value));}
(async()=>{
  let runStatus='running',runPosts=0,networkFails=true;
  const handler=async(p,m,body)=>{if(p.endsWith('/run')&&m==='POST'){runPosts++;if(networkFails)throw Error('connection lost');return {run_id:'server-run',status:'queued'};}if(p==='/automation-runs/server-run')return {item:{status:runStatus,result:{message:'safe result'}}};if(p.startsWith('/automation-runs/')){const error=Error('not registered');error.httpStatus=404;throw error;}if(p==='/automations')return {items:[]};throw Error('Unexpected '+p);};
  const first=await browser({handler});
  const action="submitAutomationRun({id:'brush1',name:'Test',enabled:true},false,document.querySelector('button'))";
  await first.run(action);assert.equal(runPosts,1);const id=first.run('[...automationState.pending.values()][0].request_id');assert(id);assert(first.calls.filter(c=>c.m==='POST').every(c=>c.p==='/automations/brush1/run'),'Run submissions use JSON body');
  await tick();await first.run(action);await tick();assert.equal(runPosts,1,'Uncertain action queries original run before offering retry');assert(first.element('#automationRunRecovery').innerHTML.includes('原编号重新提交'));
  const reopened=await browser({handler});assert.equal(reopened.run('[...automationState.pending.values()][0].request_id'),id,'Browser reopen retains UUID');networkFails=false;await reopened.run(action);await tick();assert(!reopened.calls.some(c=>c.m==='POST'));await reopened.run("retryMissingAutomationRun([...automationState.pending.values()][0],[...automationState.pending.keys()][0],automationState.dialogEpoch,document.querySelector('button'))");await tick();assert.equal(reopened.calls.find(c=>c.m==='POST').body.request_id,id,'404 confirmation reuses original UUID');assert(reopened.calls.some(c=>c.p==='/automation-runs/server-run'));
  const count=runPosts;await reopened.run(action);await tick();assert.equal(runPosts,count,'Known run only queries receipt');
  const otherAccount=await browser({username:'bob',handler});assert.equal(otherAccount.run('automationState.pending.size'),0);const otherOrigin=await browser({origin:'http://other-nas',handler});assert.equal(otherOrigin.run('automationState.pending.size'),0);
  const blocked=await browser({username:'blocked',handler});failStorage=true;await blocked.run(action);assert(!blocked.calls.some(c=>c.m==='POST'),'No run can be submitted without durable UUID');failStorage=false;
  runStatus='completed';await reopened.run("pollAutomationRun([...automationState.pending.values()][0],[...automationState.pending.keys()][0],automationState.dialogEpoch)");assert.equal(reopened.run('automationState.pending.size'),0,'Confirmed run clears durable receipt');
  const finalReopen=await browser({handler});assert.equal(finalReopen.run('automationState.pending.size'),0);

  let release;const delayed=await browser({username:'delayed',handler:async(p,m)=>p.endsWith('/run')?new Promise(resolve=>release=()=>resolve({run_id:'late',status:'queued'})):({items:[]})});
  const pending=delayed.run(action);await delayed.run(action);await tick();assert.equal(delayed.calls.filter(c=>c.m==='POST').length,1,'Double click cannot submit two in-flight runs');await delayed.run('leaveAutomations()');release();await pending;assert.equal(delayed.element('#automationDialog').open,false,'Late run acceptance cannot reopen a dialog after navigation');assert.equal(delayed.timers.size,0);assert(!delayed.calls.some(c=>c.p.endsWith('/stop')),'Navigation never stops NAS jobs');
  let resolveRead;const polling=await browser({username:'polling',handler:async p=>p.startsWith('/automation-runs/')?new Promise(resolve=>resolveRead=resolve):({items:[]})});
  polling.run("automationDialog('Run',''); automationState.dialogEpoch=7");const reading=polling.run("pollAutomationRun({run_id:'r',request_id:'q'},'key',7)");await tick();polling.run('leaveAutomations()');resolveRead({item:{status:'running',result:{message:'old'}}});await reading;assert.equal(polling.timers.size,0,'Late polling response cannot reschedule after navigation');assert(!polling.element('#automationRunResult').innerHTML.includes('old'));

  const listReads=[];const lists=await browser({username:'list-race',handler:async p=>new Promise(resolve=>listReads.push(resolve))});const oldList=lists.run('refreshAutomations()');const newList=lists.run('refreshAutomations()');listReads[1]({items:[{id:'new',kind:'brush',name:'New'}]});await newList;listReads[0]({items:[{id:'old',kind:'brush',name:'Old'}]});await oldList;assert.equal(lists.run('automationState.items[0].id'),'new','Old list request cannot overwrite fresher data');

  const creating=await browser({username:'uncertain-create',handler:async(p,m)=>{if(m==='POST')throw Error('response lost');return {items:[]};}});await creating.run("automationForm({kind:'hdfans_signin',enabled:false})");creating.element('#automationForm').values={name:'New',cookie:'fixture-only',window_start:'08:00',window_end:'10:00'};const submit=()=>creating.element('#automationForm').onsubmit({preventDefault(){},submitter:{value:'save'}});await submit();await submit();assert.equal(creating.calls.filter(c=>c.m==='POST').length,2);const creationId=creating.calls.find(c=>c.m==='POST').body.request_id;assert.equal(creating.calls.filter(c=>c.m==='POST')[1].body.request_id,creationId,'Create retry keeps original UUID');assert([...durable.values()].every(v=>!v.includes('fixture-only')),'Cookie must not be persisted in browser');const reopenedCreate=await browser({username:'uncertain-create',handler:async(p,m)=>m==='POST'?{item:{id:'created'}}:{items:[]}});await assert.rejects(reopenedCreate.run("createAutomationConfig({kind:'hdfans_signin',name:'Changed',cookie:'fixture-only',enabled:false,window_start:'08:00',window_end:'10:00'})"),/此前创建结果尚未确认/);assert(!reopenedCreate.calls.some(c=>c.m==='POST'),'Changed uncertain-create payload is not submitted');await reopenedCreate.run("createAutomationConfig({kind:'hdfans_signin',name:'New',cookie:'fixture-only',enabled:false,window_start:'08:00',window_end:'10:00'})");assert.equal(reopenedCreate.calls.find(c=>c.m==='POST').body.request_id,creationId,'Reopened create uses same UUID and same body');assert.equal(reopenedCreate.run('automationState.creates.size'),0);

  const createBlocked=await browser({username:'create-storage-block'});failStorage=true;await assert.rejects(createBlocked.run("createAutomationConfig({kind:'hdfans_signin',name:'New',cookie:'fixture-only',enabled:false,window_start:'08:00',window_end:'10:00'})"),/无法保存创建回执/);failStorage=false;assert(!createBlocked.calls.some(c=>c.m==='POST'),'Create must persist UUID before submitting');

  for(const reviewStatus of ['needs_review','interrupted']){const review=await browser({username:'review-'+reviewStatus,handler:async(p,m)=>m==='POST'?{run_id:'review',status:reviewStatus}:{item:{status:reviewStatus,result:{message:'Review'}},items:[]}});await review.run(action);await tick();assert(review.element('#automationRunRecovery').innerHTML.includes('已核查，关闭本地回执'));assert.equal(review.run('automationState.pending.size'),1);await review.element('#ackAutomationRun').onclick();assert.equal(review.run('automationState.pending.size'),0,'Review acknowledgment clears only local receipt');assert.equal(review.calls.filter(c=>c.m==='POST').length,1,'Acknowledgment performs no backend mutation');}

  const hashing=await browser({username:'http-fingerprint'});hashing.context.crypto={};for(const value of ['', 'abc', '汉字与Cookie'.repeat(500)]){hashing.context.hashInput=value;const actual=hashing.run('automationSha256(new TextEncoder().encode(hashInput))');assert.equal(actual,require('node:crypto').createHash('sha256').update(value).digest('hex'),'HTTP fallback matches standard SHA-256');}assert.equal(await hashing.run("automationFingerprint({kind:'brush',enabled:false})"),require('node:crypto').createHash('sha256').update(JSON.stringify([['enabled',false],['kind','brush']])).digest('hex'));

  const ui=await browser({username:'ui',handler:async(p,m)=>{if(p==='/sites')return {items:[]};if(p==='/downloaders')return {items:[]};if(p==='/automations/hdf')return {item:{id:'hdf',kind:'hdfans_signin',name:'Daily',has_cookie:true,cookie:'NEVER_SHOW_COOKIE',enabled:false,window_start:'08:00',window_end:'10:00'}};return {items:[]};}});
  await ui.run("automationForm({id:'hdf',kind:'hdfans_signin'})");const formHtml=ui.element('#automationDialogBody').innerHTML;assert(!formHtml.includes('NEVER_SHOW_COOKIE'));assert(formHtml.includes('留空保留'));assert(formHtml.includes('保存并保持停用'));assert(formHtml.includes('保存并启用'));assert(formHtml.includes('type="password"'));
  ui.context.form={values:{name:'Daily',cookie:'',window_start:'08:00',window_end:'10:00'}};
  const cookieBody=ui.run("automationFormBody(form,{id:'hdf',kind:'hdfans_signin',has_cookie:true},false)");assert(!Object.hasOwn(cookieBody,'cookie'));assert.equal(cookieBody.enabled,false);
  ui.context.form={values:{name:'Brush',site_id:'site1',downloader_id:'1',save_path:'',interval_minutes:'10',concurrent:'8',reserve_gib:'100',capacity_gib:'500',min_seeders:'2',min_leechers:'3',observe_hours:'6',low_upload_kib:'32'},elements:{only_free:{checked:true},auto_delete:{checked:false}}};
  const body=json(ui.run("automationFormBody(form,{kind:'brush'},false,[{id:'1',default_save_path:'/downloads'}])"));assert.equal(body.save_path,'/downloads');assert.equal(body.delete_data,false);assert.equal(body.enabled,false);assert.deepEqual(body.promotions,['FREE']);assert.equal(body.observe_hours,6);assert.throws(()=>ui.run("automationFormBody(form,{kind:'brush'},false,[])"),/保存路径/);
  ui.run("automationState.items=[{id:'a',kind:'mteam_check',name:'<script>',enabled:false,last_status:'idle',window_start:'08:00',window_end:'10:00'}];renderAutomations()");assert(ui.element('#automationList').innerHTML.includes('账户检查（非网页登录保号）'));assert(ui.element('#automationList').innerHTML.includes('&lt;script&gt;'));assert(!ui.element('#automationList').innerHTML.includes('<script>'));
  ui.run("automationState.filter='brush';renderAutomations()");assert(ui.element('#automationList').innerHTML.includes('还没有这类'));
  const safe=ui.run("automationResult({message:'request https://secret/?passkey=xyz',api_key:'SECRET',download_url:'http://token',retention:[{info_hash:'abc',reason:'obligations_unknown'}]})");assert(!safe.includes('https://secret'));assert(!safe.includes('SECRET'));assert(safe.includes('保种义务未知，保留'));
  ui.run("deleteAutomation({id:'a',name:'Test'})");assert(ui.element('#automationDialogBody').innerHTML.includes('不删除已下载文件'));
  await ui.run("automationForm({kind:'http_signin',has_cookie:true,has_headers_json:true,has_request_body:true,cookie:'SECRET_COOKIE',headers_json:'SECRET_HEADER',request_body:'SECRET_BODY'})");
  const genericHtml=ui.element('#automationDialogBody').innerHTML;
  for(const secret of ['SECRET_COOKIE','SECRET_HEADER','SECRET_BODY'])assert(!genericHtml.includes(secret),'Saved secrets never appear in HTML');
  assert(genericHtml.includes('name="signin_url"'));assert(!genericHtml.includes('name="site_id"'));
  ui.run('closeAutomationDialog()');assert.equal(ui.element('#automationDialogBody').innerHTML,'','Closing removes sensitive form nodes');
  ui.run("automationDialog('Draft','<input value=SECRET>');resetAutomations()");assert.equal(ui.element('#automationDialogBody').innerHTML,'','Logout clears draft secrets');
  ui.context.form={values:{name:'Custom',signin_url:'https://example.test/sign',method:'POST',request_format:'json',cookie:'',headers_json:'',request_body:'',success_contains:'signed',already_contains:'already',failure_contains:'failed',expected_status:'200',window_start:'08:00',window_end:'10:00'}};
  const generic=json(ui.run("automationFormBody(form,{id:'custom',kind:'http_signin'},false)"));
  assert.equal(generic.method,'POST');assert.equal(generic.expected_status,200);assert.equal(generic.success_contains,'signed');
  for(const key of ['cookie','headers_json','request_body','site_id'])assert(!Object.hasOwn(generic,key));
  Object.assign(ui.context.form.values,{cookie:'COOKIE_VALUE',headers_json:'{"Authorization":"HEADER_VALUE"}',request_body:'{"token":"BODY_VALUE"}'});
  const submitted=json(ui.run("automationFormBody(form,{kind:'http_signin'},false)"));assert.equal(submitted.request_body,'{"token":"BODY_VALUE"}');
  const secretCreate=await browser({username:'generic-private',handler:async(p,m)=>{if(m==='POST')throw Error('response lost');return {items:[]};}});
  secretCreate.context.submitted=submitted;await assert.rejects(secretCreate.run('createAutomationConfig(submitted)'),/response lost/);
  for(const secret of ['COOKIE_VALUE','HEADER_VALUE','BODY_VALUE'])assert([...durable.values()].every(v=>!v.includes(secret)),'No attendance credentials may be persisted in browser');
  ui.context.form={values:{name:'Brush',site_id:'s',downloader_id:'1',save_path:'/downloads',interval_minutes:'10',concurrent:'8',reserve_gib:'100',capacity_gib:'500',min_seeders:'2',min_leechers:'3',observe_hours:'6',low_upload_kib:'32',retention_policy:'seed_hours_ratio',min_seed_hours:'72',min_ratio:'1.5',low_leechers:'2'},elements:{only_free:{checked:true},auto_delete:{checked:true},delete_data:{checked:true}}};
  const rotation=json(ui.run("automationFormBody(form,{kind:'brush'},false)"));assert.equal(rotation.delete_data,true);assert.equal(rotation.retention_policy,'seed_hours_ratio');assert.equal(rotation.min_ratio,1.5);assert.equal(rotation.min_seed_hours,72);assert.equal(rotation.low_leechers,2);
  ui.context.form.elements.auto_delete.checked=false;assert.throws(()=>ui.run("automationFormBody(form,{kind:'brush'},false)"),/同时开启自动淘汰/);
  console.log('PASS: automation receipts, race protection, safe rendering, generic attendance form and secret-free persistence, retention policy and managed-file cleanup form, disabled defaults');
})().catch(e=>{console.error(e);process.exitCode=1;});
