const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const elements=new Map(),calls=[],stored=new Map();let failStorage=false,readHook=null;
function el(s){if(!elements.has(s))elements.set(s,{hidden:false,value:'',textContent:'',innerHTML:'',disabled:false,children:[],open:false,dataset:{},classList:{toggle(){}},setAttribute(){},addEventListener(){},querySelectorAll(){return [{value:'s'}];},querySelector(){return el('button');},append(){},showModal(){this.open=true;},close(){this.open=false;},focus(){}});return elements.get(s);}
const context=vm.createContext({console,document:{querySelector:el,createElement:()=>el('created')},location:{origin:'http://fixture'},localStorage:{getItem:k=>stored.get(k)||null,setItem(k,v){if(failStorage)throw Error('blocked');stored.set(k,v);}},crypto:require('node:crypto').webcrypto,URLSearchParams,FormData:class{},setTimeout(){return 1;},clearTimeout(){},setInterval(){},fetch:async(url,o)=>{calls.push({url,o});let d={};if(url.endsWith('/health'))d={configured:false};else if(url.includes('/searches/')){if(o.method==='DELETE')d={status:'cancelled'};else if(readHook)d=await readHook(url);else d={status:'completed',items:[],total:0,site_totals:{},errors:[]};}else if(url.endsWith('/download'))d={operation:{status:'uncertain',message:'pending'}};else if(url.includes('/operations/'))d={operation:{status:'uncertain',message:'pending'}};else throw Error('Unexpected '+url);return {ok:true,status:200,json:async()=>({ok:true,...d})};}});
const run=s=>vm.runInContext(s,context);run(fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8'));
(async()=>{await new Promise(setImmediate);run("initializePending('admin');resourceState.epoch=1;resourceState.id='search';resourceState.query='movie';resourceState.sites=[{id:'s',name:'站点'}]");
readHook=async url=>{const offset=Number(new URL(url,'http://fixture').searchParams.get('offset'));return {status:'completed',items:Array.from({length:Math.min(100,121-offset)},(_,i)=>({id:String(offset+i),site_id:'s',site_name:'站点',name:'<script>',size:1024,promotion:'FREE'})),total:121,site_totals:{s:151},errors:[]};};await run('pollResources(1)');assert.equal(run('resourceState.items.length'),121);assert(calls.some(c=>c.url.includes('offset=100')));assert(!el('#resourceMore').hidden);assert(el('#resourceResults').innerHTML.includes('&lt;script&gt;'));assert(el('#resourceStatus').textContent.includes('121.0 KB'));
let resolve;readHook=()=>new Promise(r=>resolve=r);const reading=run('pollResources(1)');await run('stopResources()');resolve({status:'completed',items:[{id:'stale',site_id:'s'}],total:1,site_totals:{}});await reading;assert.equal(run('resourceState.items.length'),121,'Stop must reject late results');assert.equal(run('resourceState.running'),false);assert(el('#resourceMore').hidden);assert(calls.some(c=>c.o.method==='DELETE'));
run("resourceState.epoch=3;resourceState.id='new'");const stale=run('pollResources(3)');run('resourceState.epoch=4;resourceState.items=[]');resolve({status:'completed',items:[{id:'old',site_id:'s'}],total:1,site_totals:{}});await stale;assert.equal(run('resourceState.items.length'),0,'New search must reject old response');
const action="operation('/sites/s/torrents/t/download',{request_id:uuid(),downloader_id:'d',save_path:'',paused:false},document.querySelector('button'))";failStorage=true;await run(action);assert.equal(calls.filter(c=>c.o.method==='POST').length,0,'Storage failure prevents download');failStorage=false;await run(action);const id=run('[...pendingOperations.values()][0]');await run(action);assert.equal(calls.filter(c=>c.o.method==='POST').length,1,'Uncertain site download cannot replay');assert(calls.some(c=>c.url.endsWith('/operations/'+id)));
console.log('PASS: resource pagination, stale/stop rejection, size and escaped names, storage failure zero POST, uncertain receipt no replay');})().catch(e=>{console.error(e);process.exitCode=1;});
