package com.nasdownload.app;
import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import android.text.InputType;
import org.json.*;
import java.util.*;
import java.util.concurrent.*;
import java.io.*;

public class MainActivity extends Activity {
 final int green=Color.rgb(19,133,115), ink=Color.rgb(31,48,44), muted=Color.rgb(102,118,111), bg=Color.rgb(239,245,242);
 final ExecutorService worker=Executors.newSingleThreadExecutor();final Api api=new Api();TokenStore store;LinearLayout root,body,tabRow;TextView status,summary;ScrollView scroll;Spinner select;EditText search;JSONArray downloaders=new JSONArray();String chosen="all",state="all";int offset=0,total=0;boolean rendering=false,busy=false;long viewEpoch;byte[] torrent;TextView torrentLabel;float touchX,touchY;String setupCode="";
 interface Work {JSONObject run()throws Exception;}interface Done {void accept(JSONObject j)throws Exception;}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(bg);store=new TokenStore(this);api.base=store.base();api.token=store.token();if(api.token.isEmpty())welcome();else home();}
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
 LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 TextView text(String s,int sp,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(color);t.setPadding(dp(2),dp(5),dp(2),dp(5));return t;}
 Button button(String s,Runnable r){Button b=new Button(this);b.setText(s);b.setTextColor(green);b.setAllCaps(false);b.setMinHeight(dp(44));b.setPadding(dp(8),dp(4),dp(8),dp(4));b.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x22138573),shape(Color.WHITE),null));b.setMinWidth(0);b.setMinimumWidth(0);b.setOnClickListener(v->r.run());return b;}
 void addFill(LinearLayout l,View v){l.addView(v,new LinearLayout.LayoutParams(-1,-2));}void weight(LinearLayout l,View v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(dp(2),dp(3),dp(2),dp(3));l.addView(v,p);}
 GradientDrawable shape(int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(14));return d;}
 LinearLayout card(){LinearLayout l=col();l.setBackground(shape(Color.WHITE));l.setPadding(dp(12),dp(8),dp(12),dp(8));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(6));l.setLayoutParams(p);return l;}
 EditText input(LinearLayout form,String label,String value,boolean secret){TextView t=text(label,13,muted);form.addView(t);EditText e=new EditText(this);e.setSingleLine(true);e.setText(value);e.setTextSize(15);e.setInputType(secret?InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD:InputType.TYPE_CLASS_TEXT);form.addView(e,new LinearLayout.LayoutParams(-1,-2));return e;}
 String value(EditText e){return e.getText().toString().trim();}
 void screen(String title){viewEpoch++;root=col();root.setPadding(dp(16),dp(16),dp(16),dp(8));root.setBackgroundColor(bg);if(Build.VERSION.SDK_INT>=35)root.setOnApplyWindowInsetsListener((v,i)->{android.graphics.Insets ins=i.getInsets(WindowInsets.Type.systemBars());v.setPadding(dp(16),dp(8)+ins.top,dp(16),dp(8)+ins.bottom);return i;});TextView heading=text(title,24,ink);heading.setTypeface(null,Typeface.BOLD);root.addView(heading);status=text("",13,muted);root.addView(status);status.setVisibility(View.GONE);scroll=new ScrollView(this);body=col();scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 void call(String label,Work work,Done done){performCall(label,work,done,false);}
 void read(String label,Work work,Done done){performCall(label,work,done,true);}
 void performCall(String label,Work work,Done done,boolean guard){if(busy){Toast.makeText(this,"请等待当前请求完成",Toast.LENGTH_SHORT).show();return;}busy=true;long epoch=viewEpoch;status.setTextColor(muted);status.setVisibility(View.VISIBLE);status.setText(label);worker.execute(()->{try{JSONObject j=work.run();runOnUiThread(()->{busy=false;if(guard&&(epoch!=viewEpoch||isFinishing()||isDestroyed()))return;status.setText("");status.setVisibility(View.GONE);try{done.accept(j);}catch(Exception e){error(e.getMessage());}});}catch(Exception e){runOnUiThread(()->{busy=false;if(guard&&(epoch!=viewEpoch||isFinishing()||isDestroyed()))return;if(e instanceof Api.Failure&&((Api.Failure)e).status==401&&!api.token.isEmpty()){store.clear();api.token="";welcome();error("登录已失效，请重新连接。");}else error(e.getMessage());});}});} void error(String s){status.setVisibility(View.VISIBLE);status.setText(s==null?"请求失败":s);status.setTextColor(Color.rgb(170,57,45));Toast.makeText(this,s==null?"请求失败":s,Toast.LENGTH_LONG).show();}
 JSONObject json(Object... pairs)throws Exception{JSONObject j=new JSONObject();for(int i=0;i<pairs.length;i+=2)j.put((String)pairs[i],pairs[i+1]);return j;}
 void welcome(){screen("Nas Download");body.addView(text("把 NAS 下载任务装进口袋",19,ink));body.addView(text("自带下载能力 · 手机与网页同步管理\n连接地址由你填写，不内置任何私人 NAS。",14,muted));body.addView(button("连接已有 NAS",()->connect(false)));body.addView(button("自动安装",this::installForm));body.addView(text("自动安装需要：Linux NAS、已开启 SSH、Docker Compose，以及当前账号的容器权限。",13,muted));}
 void connect(boolean setup){screen(setup?"创建管理员":"连接已有 NAS");body.addView(button("‹ 返回",this::welcome));EditText url=input(body,"服务地址（如 http://192.168.1.10:7120）",api.base,false);body.addView(text("支持局域网与 Tailscale 数字 IP。HTTP 本身不加密；使用 Tailscale 前，手机与 NAS 须登录同一网络。公网请使用 HTTPS。",12,muted));EditText name=input(body,"管理员账号","",false),pass=input(body,"密码","",true),code=input(body,setup?"安装生成的初始化码":"配对码（可代替账号密码）",setupCode,false);body.addView(button(setup?"创建并进入":"连接",()->{if(busy)return;try{api.base=UrlPolicy.normalize(value(url));String p=pass.getText().toString();if(setup&&p.length()<10)throw new Exception("管理员密码至少 10 个字符");String path=setup?"/setup":value(code).isEmpty()?"/login":"/pair";JSONObject payload=setup?json("setup_token",value(code),"username",value(name),"password",p):path.equals("/pair")?json("code",value(code),"label",Build.MODEL):json("username",value(name),"password",p,"label",Build.MODEL);call("正在连接…",()->api.request("POST",path,payload),j->{store.save(api.base,j.getString("token"));api.token=j.getString("token");pass.setText("");code.setText("");setupCode="";home();});}catch(Exception e){error(e.getMessage());}}));if(!setup)body.addView(button("首次安装：创建管理员",()->{if(busy)return;try{api.base=UrlPolicy.normalize(value(url));connect(true);}catch(Exception e){error(e.getMessage());}}));}
 void home(){screen("下载任务");LinearLayout actions=row();weight(actions,button("＋ 添加",this::addTask));weight(actions,button("站点搜索",this::siteSearch));weight(actions,button("刷新",()->loadTasks(true)));weight(actions,button("更多",this::menu));body.addView(actions);select=new Spinner(this);body.addView(select);search=new EditText(this);search.setSingleLine(true);search.setHint("搜索任务名称");search.setTextSize(14);search.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH);search.setOnEditorActionListener((v,a,e)->{loadTasks(true);return true;});body.addView(search);tabRow=row();body.addView(tabRow);summary=text("",13,muted);body.addView(summary);scroll.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN){touchX=e.getX();touchY=e.getY();}else if(e.getAction()==MotionEvent.ACTION_UP){float dx=e.getX()-touchX,dy=e.getY()-touchY;if(Math.abs(dx)>dp(90)&&Math.abs(dx)>Math.abs(dy)*1.5){String[] s={"all","downloading","completed","paused"};int pos=Arrays.asList(s).indexOf(state);state=s[Math.max(0,Math.min(3,pos+(dx<0?1:-1)))];loadTasks(true);}else if(dy>dp(110)&&scroll.getScrollY()==0)loadTasks(true);}return false;});read("读取下载器…",()->api.request("GET","/downloaders",null),j->{downloaders=j.getJSONArray("items");ArrayList<String> names=new ArrayList<>();names.add("全部下载器");for(int i=0;i<downloaders.length();i++)names.add(downloaders.getJSONObject(i).optString("name"));rendering=true;select.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));int index=0;for(int i=0;i<downloaders.length();i++)if(downloaders.getJSONObject(i).optString("id").equals(chosen))index=i+1;if(index==0)chosen="all";select.setSelection(index);rendering=false;select.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int n,long id){String next=n==0?"all":downloaders.optJSONObject(n-1).optString("id");if(!rendering&&!next.equals(chosen)){chosen=next;loadTasks(true);}}});loadTasks(true);});}
 int fixedChildren=5;
 void loadTasks(boolean reset){if(search==null)return;String requestedState=state,requestedDownloader=chosen,requestedQuery=value(search);if(reset)offset=0;String q="/tasks?downloader_id="+Api.segment(chosen)+"&state="+state+"&query="+Api.segment(value(search))+"&offset="+offset+"&limit=50";read("读取任务…",()->api.request("GET",q,null),j->{if(!requestedState.equals(state)||!requestedDownloader.equals(chosen)||!requestedQuery.equals(value(search))){loadTasks(true);return;}while(body.getChildCount()>fixedChildren)body.removeViewAt(fixedChildren);total=j.optInt("total");JSONObject sums=j.optJSONObject("summary");if(sums==null)sums=new JSONObject();tabRow.removeAllViews();String[] ids={"all","downloading","completed","paused"},labels={"全部","下载","完成","暂停"};for(int i=0;i<ids.length;i++){final String s=ids[i];Button b=button(labels[i]+" "+sums.optInt(s.equals("all")?"total":s),()->{state=s;loadTasks(true);});b.setTextSize(12);b.setSingleLine();if(state.equals(s)){b.setTypeface(null,Typeface.BOLD);b.setTextColor(ink);b.setBackground(shape(0xffdaeee7));}weight(tabRow,b);}summary.setText("↓ "+bytes(sums.optDouble("download_speed"))+"/s   ↑ "+bytes(sums.optDouble("upload_speed"))+"/s   共 "+total+" 项");JSONArray errors=j.optJSONArray("errors");if(errors!=null)for(int i=0;i<errors.length();i++)body.addView(text(errors.getJSONObject(i).optString("error"),13,Color.RED));JSONArray items=j.optJSONArray("items");if(items==null||items.length()==0){body.addView(text(downloaders.length()==0?"还没有下载器，请在“更多 → 下载器管理”中添加并验证连接。":"此分类没有任务。可切换“全部”，或使用“添加”导入磁力链接 / 种子。",15,muted));}else for(int i=0;i<items.length();i++)taskCard(items.getJSONObject(i));LinearLayout paging=row();if(offset>0)weight(paging,button("上一页",()->{offset=Math.max(0,offset-50);loadTasks(false);}));if(offset+50<total)weight(paging,button("下一页",()->{offset+=50;loadTasks(false);}));body.addView(paging);body.setAlpha(.35f);body.animate().alpha(1).setDuration(180).start();});}
 static String bytes(double n){if(Double.isNaN(n)||Double.isInfinite(n)||n<0)n=0;if(n<1024)return String.format(Locale.US,"%.0f B",n);String[] u={"KB","MB","GB","TB"};n/=1024;int i=0;while(n>=1024&&i<3){n/=1024;i++;}return String.format(Locale.US,"%.1f %s",n,u[i]);}
 String taskId(JSONObject t){return t.optString("id",t.optString("hash"));}String downloaderId(JSONObject t){return t.optString("downloader_id",chosen);}
 String stateLabel(String s){switch(s){case "downloading":return "下载中";case "paused":return "已暂停";case "completed":return "已完成";case "seeding":return "做种中";case "checking":return "校验中";case "queued":return "排队中";case "error":return "错误";default:return s.isEmpty()?"状态未知":s;}}
 void taskCard(JSONObject t){LinearLayout c=card();TextView name=text(t.optString("name","未命名任务"),16,ink);name.setTypeface(null,Typeface.BOLD);c.addView(name);double p=t.optDouble("progress",0);if(p>1)p/=100;p=Math.max(0,Math.min(1,p));ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(1000);bar.setProgress((int)(p*1000));bar.setProgressTintList(android.content.res.ColorStateList.valueOf(green));c.addView(bar,new LinearLayout.LayoutParams(-1,dp(8)));c.addView(text(t.optString("state_label",stateLabel(t.optString("state")))+" · "+String.format(Locale.US,"%.1f%%",p*100)+" · "+bytes(t.optDouble("size",t.optDouble("total_size"))),13,muted));c.addView(text("↓ "+bytes(t.optDouble("download_speed"))+"/s   ↑ "+bytes(t.optDouble("upload_speed"))+"/s",13,muted));c.setOnClickListener(v->detail(t));body.addView(c);}
 void detail(JSONObject task){String path="/tasks/"+Api.segment(downloaderId(task))+"/"+Api.segment(taskId(task));read("读取任务详情…",()->api.request("GET",path,null),j->{LinearLayout f=col();JSONObject t=j.optJSONObject("item");if(t==null)t=task;f.addView(text(t.optString("name"),18,ink));f.addView(text(t.optString("state_label",stateLabel(t.optString("state")))+" · "+bytes(t.optDouble("total_size",t.optDouble("size",0)))+"\n保存目录："+t.optString("save_path","未提供"),13,muted));LinearLayout buttons=row();boolean paused=t.optString("state").equals("paused");String control=paused?"继续":t.optString("state").equals("completed")||t.optDouble("progress",0)>=1?"暂停做种":"暂停下载";weight(buttons,button(control,()->action(task,paused?"resume":"pause",false)));weight(buttons,button("删除",()->deleteTask(task)));f.addView(buttons);f.addView(text("文件",16,ink));JSONArray files=j.optJSONArray("files");if(files!=null)for(int i=0;i<files.length();i++){JSONObject item=files.getJSONObject(i);f.addView(text(item.optString("name")+"\n"+bytes(item.optDouble("size"))+" · "+String.format(Locale.US,"%.1f%%",item.optDouble("progress",0)*100),13,muted));}f.addView(text("Tracker",16,ink));JSONArray tr=j.optJSONArray("trackers");if(tr!=null)for(int i=0;i<tr.length();i++){JSONObject x=tr.getJSONObject(i);f.addView(text(x.optString("url")+"\n"+x.optString("status")+" "+x.optString("message"),12,muted));}dialog("任务详情",f,null,null);});}
 void deleteTask(JSONObject t){LinearLayout f=col();f.addView(text("从下载器删除“"+t.optString("name")+"”？",15,ink));CheckBox data=new CheckBox(this);data.setText("同时删除下载文件（不可恢复）");f.addView(data);dialog("删除任务",f,"删除",()->action(t,"delete",data.isChecked()));}
 void action(JSONObject t,String action,boolean deleteData){try{mutate("/tasks/"+Api.segment(downloaderId(t))+"/"+Api.segment(taskId(t))+"/action",json("action",action,"delete_data",deleteData));}catch(Exception e){error(e.getMessage());}}
 static String canonical(Object value)throws Exception {
  if(value instanceof JSONObject){JSONObject j=(JSONObject)value;TreeSet<String> keys=new TreeSet<>();Iterator<String> iterator=j.keys();while(iterator.hasNext()){String key=iterator.next();if(!key.equals("request_id"))keys.add(key);}StringBuilder out=new StringBuilder("{");for(String key:keys){if(out.length()>1)out.append(',');out.append(JSONObject.quote(key)).append(':').append(canonical(j.get(key)));}return out.append('}').toString();}
  if(value instanceof JSONArray){JSONArray a=(JSONArray)value;StringBuilder out=new StringBuilder("[");for(int i=0;i<a.length();i++){if(i>0)out.append(',');out.append(canonical(a.get(i)));}return out.append(']').toString();}
  if(value==null||value==JSONObject.NULL)return "null";if(value instanceof String)return JSONObject.quote((String)value);return value.toString();
 }
 String signature(String path,JSONObject payload)throws Exception {byte[] digest=java.security.MessageDigest.getInstance("SHA-256").digest((api.base+"\n"+path+"\n"+canonical(payload)).getBytes("UTF-8"));return "sig:"+android.util.Base64.encodeToString(digest,android.util.Base64.NO_WRAP);}
 void clearReceipt(String id){android.content.SharedPreferences p=getSharedPreferences("operations",0);android.content.SharedPreferences.Editor e=p.edit().remove(id);for(Map.Entry<String,?> x:p.getAll().entrySet())if(x.getKey().startsWith("sig:")&&id.equals(x.getValue()))e.remove(x.getKey());e.commit();}
 void mutate(String path,JSONObject payload)throws Exception {
  if(busy)throw new Exception("请等待当前请求完成");android.content.SharedPreferences p=getSharedPreferences("operations",0);String sig=signature(path,payload),known=p.getString(sig,"");
  if(!known.isEmpty()){receipt(known);return;}
  String id=UUID.randomUUID().toString();payload.put("request_id",id);
  if(!p.edit().putString(id,api.base).putString(sig,id).commit())throw new Exception("无法保存操作编号，未发送请求");
  call("提交操作…",()->{try{return api.request("POST",path,payload);}catch(Exception first){if(first instanceof Api.Failure&&((Api.Failure)first).status>=400&&((Api.Failure)first).status<500){clearReceipt(id);throw first;}try{return api.request("GET","/operations/"+id,null);}catch(Exception second){return json("ok",true,"operation",json("request_id",id,"status","uncertain","message","响应未知。请在操作记录中查询回执，不要重复添加或删除。"));}}},j->{JSONObject op=j.optJSONObject("operation");if(op!=null&&"completed".equals(op.optString("status")))clearReceipt(id);String msg=op==null?"已提交":op.optString("message",op.optString("status"));new AlertDialog.Builder(this).setTitle("操作回执").setMessage(msg+"\n编号："+id).setPositiveButton("确定",(d,w)->{if(path.startsWith("/sites/"))home();else loadTasks(true);}).show();});
 } void dialog(String title,LinearLayout form,String positive,Runnable action){ScrollView sv=new ScrollView(this);form.setPadding(dp(18),dp(8),dp(18),dp(8));sv.addView(form);AlertDialog.Builder b=new AlertDialog.Builder(this).setTitle(title).setView(sv).setNegativeButton("关闭",null);if(positive!=null)b.setPositiveButton(positive,null);AlertDialog d=b.create();d.show();if(positive!=null)d.getButton(-1).setOnClickListener(v->{action.run();if(busy)d.dismiss();});}
 void addTask(){if(downloaders.length()==0){error("请先添加下载器");return;}torrent=null;LinearLayout f=col();Spinner d=new Spinner(this);ArrayList<String> names=new ArrayList<>();int ix=0;for(int i=0;i<downloaders.length();i++){JSONObject x=downloaders.optJSONObject(i);names.add(x.optString("name"));if(x.optString("id").equals(chosen))ix=i;}d.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));d.setSelection(ix);f.addView(d);EditText url=input(f,"磁力链接 / 种子 URL","",false),save=input(f,"保存目录（留空使用下载器默认值）","",false);torrentLabel=text("未选择种子文件",13,muted);f.addView(torrentLabel);f.addView(button("选择 .torrent 文件",()->{Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT);intent.setType("*/*");intent.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(intent,9);}));CheckBox paused=new CheckBox(this);paused.setText("添加后暂停");f.addView(paused);dialog("添加下载",f,"添加",()->{try{if(torrent==null&&value(url).isEmpty())throw new Exception("请输入链接或选择种子文件");JSONObject x=json("downloader_id",downloaders.getJSONObject(d.getSelectedItemPosition()).getString("id"),"paused",paused.isChecked());if(torrent!=null)x.put("torrent_base64",android.util.Base64.encodeToString(torrent,android.util.Base64.NO_WRAP));else x.put("url",value(url));if(!value(save).isEmpty())x.put("save_path",value(save));mutate("/tasks/add",x);}catch(Exception e){error(e.getMessage());Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}});}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==9&&c==RESULT_OK&&data!=null){try(InputStream in=getContentResolver().openInputStream(data.getData());ByteArrayOutputStream b=new ByteArrayOutputStream()){byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1){if(b.size()+n>2*1024*1024)throw new Exception("种子文件不能超过 2 MB");b.write(buf,0,n);}torrent=b.toByteArray();torrentLabel.setText("已选择种子 · "+bytes(torrent.length));}catch(Exception e){error(e.getMessage());}}}
 void menu(){new AlertDialog.Builder(this).setTitle("更多").setItems(new String[]{"下载器管理","手机配对码","已登录设备","操作记录与待确认回执","打开网页","退出登录","站点配置","签到与刷流"},(d,w)->{switch(w){case 7:new AutomationUi(this).list();break;case 6:siteManage();break;case 0:manage();break;case 1:call("生成配对码…",()->api.request("POST","/pair-codes",json("label",Build.MODEL)),j->new AlertDialog.Builder(this).setTitle("手机配对码").setMessage(j.getString("code")+"\n5 分钟内有效，仅能使用一次。").setPositiveButton("确定",null).show());break;case 2:devices();break;case 3:history();break;case 4:startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(api.base)));break;case 5:call("退出登录…",()->api.request("POST","/logout",new JSONObject()),j->{store.clear();api.token="";welcome();});}}).show();}
 void manage(){read("读取下载器…",()->api.request("GET","/downloaders",null),j->{downloaders=j.getJSONArray("items");LinearLayout f=col();f.addView(button("＋ 添加下载器",()->downloaderForm(null)));for(int i=0;i<downloaders.length();i++){JSONObject x=downloaders.getJSONObject(i);f.addView(button(x.optString("name")+" · "+x.optString("type"),()->downloaderForm(x)));}dialog("下载器管理",f,null,null);});}
 void downloaderForm(JSONObject old){LinearLayout f=col();Spinner type=new Spinner(this);type.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"qBittorrent","Transmission"}));type.setSelection(old!=null&&old.optString("type").equals("transmission")?1:0);f.addView(type);EditText name=input(f,"名称",old==null?"":old.optString("name"),false),url=input(f,"下载器地址",old==null?"":old.optString("url"),false),user=input(f,"用户名","",false),pass=input(f,"密码（编辑留空保持原密码）","",true),save=input(f,"默认保存目录",old==null?"":old.optString("default_save_path"),false);f.addView(text("地址由 NAS 服务访问；下载器账号密码由服务端加密保存，手机不保存。",12,muted));Runnable test=()->{try{JSONObject p=downloaderPayload(type,name,url,user,pass,save,old);if(old!=null)p.put("downloader_id",old.get("id"));call("测试连接…",()->api.request("POST","/downloaders/test",p),j->new AlertDialog.Builder(this).setMessage("连接成功 · "+j.optString("version")).setPositiveButton("确定",null).show());}catch(Exception e){error(e.getMessage());}};f.addView(button("测试连接",test));if(old!=null)f.addView(button("移除接入",()->new AlertDialog.Builder(this).setMessage("移除该下载器接入？下载任务不会删除。").setNegativeButton("取消",null).setPositiveButton("移除",(d,w)->call("移除接入…",()->api.request("DELETE","/downloaders/"+Api.segment(old.optString("id")),null),j->home())).show()));dialog(old==null?"添加下载器":"编辑下载器",f,"保存",()->{try{JSONObject p=downloaderPayload(type,name,url,user,pass,save,old);call("验证并保存…",()->api.request(old==null?"POST":"PATCH",old==null?"/downloaders":"/downloaders/"+Api.segment(old.optString("id")),p),j->{pass.setText("");home();});}catch(Exception e){error(e.getMessage());}});}
 JSONObject downloaderPayload(Spinner type,EditText name,EditText url,EditText user,EditText pass,EditText save,JSONObject old)throws Exception{if(value(name).isEmpty()||value(url).isEmpty())throw new Exception("请填写名称和下载器地址");JSONObject j=json("name",value(name),"type",type.getSelectedItemPosition()==0?"qbittorrent":"transmission","url",value(url),"default_save_path",value(save));if(old==null||!value(user).isEmpty())j.put("username",value(user));if(old==null||!value(pass).isEmpty())j.put("password",pass.getText().toString());return j;}
 void devices(){read("读取设备…",()->api.request("GET","/devices",null),j->{LinearLayout f=col();JSONArray list=j.getJSONArray("items");for(int i=0;i<list.length();i++){JSONObject x=list.getJSONObject(i);f.addView(text(x.optString("label")+(x.optBoolean("current")?"（当前）":""),15,ink));f.addView(button("撤销会话",()->new AlertDialog.Builder(this).setMessage("撤销此设备的登录权限？").setNegativeButton("取消",null).setPositiveButton("撤销",(d,w)->call("撤销会话…",()->api.request("DELETE","/devices/"+Api.segment(x.optString("id")),null),r->{if(x.optBoolean("current")){store.clear();api.token="";welcome();}else devices();})).show()));}dialog("已登录设备",f,null,null);});}
 void history(){read("读取操作记录…",()->api.request("GET","/history?limit=50",null),j->{LinearLayout f=col();Map<String,?> pending=getSharedPreferences("operations",0).getAll();for(Map.Entry<String,?> x:pending.entrySet())if(api.base.equals(x.getValue()))f.addView(button("查询待确认回执 "+x.getKey().substring(0,8),()->receipt(x.getKey())));JSONArray list=j.optJSONArray("items");if(list!=null)for(int i=0;i<list.length();i++){JSONObject x=list.getJSONObject(i);String id=x.optString("request_id");f.addView(text(x.optString("status")+" · "+x.optString("message")+"\n"+id,13,ink));}dialog("操作记录",f,null,null);});}
 void receipt(String id){call("查询回执（不会重新执行）…",()->api.request("GET","/operations/"+id,null),j->{JSONObject op=j.getJSONObject("operation");if("completed".equals(op.optString("status")))clearReceipt(id);new AlertDialog.Builder(this).setTitle("操作回执").setMessage(op.optString("status")+"\n"+op.optString("message")).setPositiveButton("确定",null).show();});}
 void installForm(){screen("自动安装");body.addView(button("‹ 返回",this::welcome));body.addView(text("安装一个 Nas Download 产品，自带下载能力。当前 SSH 账号必须已能运行 Docker Compose；不自动安装 Docker，也不提权。",13,muted));EditText host=input(body,"SSH 主机（IP / 主机名）","",false),port=input(body,"SSH 端口","22",false),user=input(body,"SSH 用户名","",false),pass=input(body,"SSH 密码（只在内存使用）","",true),dir=input(body,"安装目录（绝对路径）","/volume1/docker/nas-download",false),bind=input(body,"服务监听地址","0.0.0.0",false);EditText servicePort=input(body,"服务端口（1024–65534）","7120",false);servicePort.setInputType(InputType.TYPE_CLASS_NUMBER);Spinner mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"内置下载（推荐）","高级：接入已有下载器"}));body.addView(mode);EditText downloads=input(body,"下载保存目录（可留空）","",false);body.addView(text("首次连接必须核对 NAS 的 SSH 主机指纹。监听 0.0.0.0 允许局域网访问；请勿将服务端口映射到公网。",12,muted));body.addView(button("验证并安装",()->{if(busy)return;try{String h=value(host),u=value(user),secret=pass.getText().toString(),folder=value(dir),b=value(bind),down=value(downloads),installMode=UrlPolicy.installMode(mode.getSelectedItemPosition());int sp=Integer.parseInt(value(servicePort));UrlPolicy.servicePort(sp);int p=Integer.parseInt(value(port));if(p<1||p>65535||h.isEmpty()||u.isEmpty()||secret.isEmpty())throw new Exception("请完整填写 SSH 连接信息");UrlPolicy.absoluteDir(folder);busy=true;long installEpoch=viewEpoch;pass.setText("");status.setVisibility(View.VISIBLE);status.setText("连接 SSH…");worker.execute(()->{try{String out=SshInstaller.install(this,h,p,u,secret,folder,b,sp,down,installMode,(identity,fp)->confirmHost(identity,fp),msg->runOnUiThread(()->{if(installEpoch==viewEpoch&&!isFinishing()&&!isDestroyed())status.setText(msg);}));InstallerResult installed=InstallerResult.parse(out,h,sp);String resultUrl=installed.url,resultCode=installed.setupCode;runOnUiThread(()->{busy=false;if(installEpoch!=viewEpoch||isFinishing()||isDestroyed())return;try{api.base=UrlPolicy.normalize(resultUrl.replace("<host>",h).replace("0.0.0.0",h));setupCode=resultCode;if(setupCode.isEmpty()){status.setText("服务安装已完成。未返回初始化码，请检查安装目录中的首次配置说明。");connect(false);}else connect(true);}catch(Exception e){error("服务已安装，但自动连接失败。请手动连接：http://"+h+":"+sp);}});}catch(Exception e){runOnUiThread(()->{busy=false;if(installEpoch!=viewEpoch||isFinishing()||isDestroyed())return;error("安装未完成："+e.getMessage());});}});}catch(Exception e){error(e.getMessage());}}));}
 boolean confirmHost(String identity,String fingerprint){CountDownLatch latch=new CountDownLatch(1);boolean[] yes={false};runOnUiThread(()->new AlertDialog.Builder(this).setTitle("确认 NAS 的 SSH 指纹").setMessage(identity+"\n\n"+fingerprint+"\n\n请与 NAS 的 SSH 主机公钥指纹核对。确认后保存；后续指纹变化会拒绝连接。").setCancelable(false).setNegativeButton("取消",(d,w)->latch.countDown()).setPositiveButton("已核对，信任",(d,w)->{yes[0]=true;latch.countDown();}).show());try{if(!latch.await(5,TimeUnit.MINUTES))return false;}catch(InterruptedException e){return false;}return yes[0];}
 @Override protected void onDestroy(){viewEpoch++;worker.shutdownNow();super.onDestroy();}

 void siteManage(){read("读取站点…",()->api.request("GET","/sites",null),j->{LinearLayout f=col();f.addView(text("填写自己的站点 API Key。密钥仅送到你的 NAS 服务；编辑留空保留原密钥。",13,muted));f.addView(button("＋ 添加站点",()->siteForm(null)));JSONArray a=j.getJSONArray("items");for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);f.addView(button(x.optString("name")+(x.optBoolean("enabled")?" · 已启用":" · 已停用"),()->siteForm(x)));}dialog("站点配置",f,null,null);});}
 void siteForm(JSONObject old){LinearLayout f=col();EditText name=input(f,"名称",old==null?"":old.optString("name"),false);Spinner type=new Spinner(this);type.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"M-Team","Torznab / Jackett / Prowlarr"}));type.setSelection(old!=null&&old.optString("type").equals("torznab")?1:0);f.addView(type);EditText url=input(f,"完整 API 地址（HTTPS）",old==null?"":old.optString("url"),false),key=input(f,"API Key（修改时留空保留）","",true);f.addView(text("M-Team：https://api.m-team.cc/api；其他站点填写 Torznab API 完整路径。",12,muted));CheckBox enabled=new CheckBox(this);enabled.setText("启用搜索");enabled.setChecked(old==null||old.optBoolean("enabled"));f.addView(enabled);if(old!=null)f.addView(button("移除此站点",()->new AlertDialog.Builder(this).setMessage("移除站点配置？下载任务仍保留。").setPositiveButton("移除",(d,w)->call("移除站点…",()->api.request("DELETE","/sites/"+Api.segment(old.optString("id")),null),j->siteManage())).setNegativeButton("取消",null).show()));dialog("站点配置",f,"保存",()->{try{JSONObject x=json("name",value(name),"type",type.getSelectedItemPosition()==0?"mteam":"torznab","url",value(url),"enabled",enabled.isChecked());if(!value(key).isEmpty())x.put("api_key",value(key));call("保存站点…",()->api.request(old==null?"POST":"PATCH",old==null?"/sites":"/sites/"+Api.segment(old.optString("id")),x),j->{key.setText("");siteManage();});}catch(Exception e){error(e.getMessage());}});}
 String activeSearch="";long searchIntent;int sitePage=1;EditText siteQuery;LinearLayout siteResults;
 void siteSearch(){screen("站点搜索");body.addView(button("‹ 下载任务",()->{cancelSiteSearch();home();}));body.addView(button("站点配置",()->{cancelSiteSearch();siteManage();}));siteQuery=input(body,"关键词（搜索已启用站点）","",false);body.addView(button("搜索",()->startSiteSearch(1)));body.addView(button("停止当前搜索",()->{if(activeSearch.isEmpty()){error("当前没有搜索");return;}String id=activeSearch;call("停止搜索…",()->api.request("DELETE","/searches/"+Api.segment(id),null),j->{activeSearch="";status.setText("搜索已停止");});}));siteResults=col();body.addView(siteResults);siteResults.addView(text("先配置自己的站点 API Key，再输入关键词搜索。站点故障会单独显示。",14,muted));}
 void startSiteSearch(int page){if(busy){error("请等待当前请求完成");return;}final String query=value(siteQuery);if(query.isEmpty()){error("请输入关键词");return;}final long epoch=viewEpoch,intent=++searchIntent;final EditText requestedInput=siteQuery;final String old=activeSearch;sitePage=page;busy=true;status.setVisibility(View.VISIBLE);status.setTextColor(muted);status.setText("开始搜索…");worker.execute(()->{try{if(!old.isEmpty())api.request("DELETE","/searches/"+Api.segment(old),null);JSONObject result=api.request("POST","/searches",json("query",query,"page",page,"limit",30));String id=result.getString("search_id");runOnUiThread(()->{busy=false;if(epoch!=viewEpoch||intent!=searchIntent||requestedInput!=siteQuery||!query.equals(value(requestedInput))||isFinishing()||isDestroyed()){cancelSearchId(id);return;}activeSearch=id;status.setVisibility(View.GONE);siteResults.removeAllViews();pollSiteSearch(id,epoch);});}catch(Exception e){runOnUiThread(()->{busy=false;if(epoch==viewEpoch&&intent==searchIntent&&!isFinishing()&&!isDestroyed())error(e.getMessage());});}});}
 void pollSiteSearch(String id,long epoch){if(epoch!=viewEpoch||!id.equals(activeSearch))return;if(busy){new Handler(getMainLooper()).postDelayed(()->pollSiteSearch(id,epoch),1000);return;}read("搜索中…",()->{JSONObject result=api.request("GET","/searches/"+Api.segment(id)+"?offset=0&limit=100",null);if(!result.optString("status").equals("running")){JSONArray all=result.optJSONArray("items");if(all!=null){int fetched=all.length(),count=result.optInt("total");while(fetched<count){JSONObject batch=api.request("GET","/searches/"+Api.segment(id)+"?offset="+fetched+"&limit=100",null);JSONArray more=batch.optJSONArray("items");if(more==null||more.length()==0)break;for(int i=0;i<more.length();i++)all.put(more.get(i));fetched=all.length();}}}return result;},j->{if(epoch!=viewEpoch||!id.equals(activeSearch))return;siteResults.removeAllViews();JSONArray errors=j.optJSONArray("errors");if(errors!=null)for(int i=0;i<errors.length();i++){JSONObject e=errors.optJSONObject(i);siteResults.addView(text(e==null?errors.optString(i):e.optString("site_name",e.optString("site_id"))+"："+e.optString("error"),13,Color.RED));}JSONArray a=j.optJSONArray("items");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);LinearLayout c=card();c.addView(text(x.optString("name"),16,ink));c.addView(text(x.optString("site_name")+" · "+bytes(x.optDouble("size"))+" · 做种 "+x.optInt("seeders")+" · "+x.optString("promotion"),12,muted));c.addView(button("详情 / 下载",()->siteDetail(x)));siteResults.addView(c);}String st=j.optString("status");if(st.equals("running")){siteResults.addView(text("正在查询站点…",13,muted));new Handler(getMainLooper()).postDelayed(()->pollSiteSearch(id,epoch),1200);}else{activeSearch="";if(a==null||a.length()==0)siteResults.addView(text(st.equals("cancelled")?"搜索已停止":"没有匹配结果。请检查关键词、站点启用状态和 API Key。",14,muted));LinearLayout paging=row();if(sitePage>1)weight(paging,button("上一页",()->startSiteSearch(sitePage-1)));if(a!=null&&a.length()>0&&hasSiteNext(j))weight(paging,button("下一页",()->startSiteSearch(sitePage+1)));siteResults.addView(paging);}});}
 boolean hasSiteNext(JSONObject j){JSONObject totals=j.optJSONObject("site_totals");if(totals==null)return false;Iterator<String> keys=totals.keys();while(keys.hasNext())if(totals.optInt(keys.next())>sitePage*30)return true;return false;}
 void cancelSiteSearch(){searchIntent++;String id=activeSearch;activeSearch="";cancelSearchId(id);}
 void cancelSearchId(String id){if(!id.isEmpty())worker.execute(()->{try{api.request("DELETE","/searches/"+Api.segment(id),null);}catch(Exception ignored){}});}
 void siteDetail(JSONObject item){String path="/sites/"+Api.segment(item.optString("site_id"))+"/torrents/"+Api.segment(item.optString("id"));read("读取种子详情…",()->api.request("GET",path,null),j->{JSONObject x=j.getJSONObject("item");LinearLayout f=col();f.addView(text(x.optString("name"),18,ink));f.addView(text(x.optString("subtitle")+"\n"+bytes(x.optDouble("size"))+" · 做种 "+x.optInt("seeders")+"\n"+x.optString("description"),13,muted));f.addView(button("选择下载器并下载",()->siteDownload(path,x)));dialog("种子详情",f,null,null);});}
 void siteDownload(String path,JSONObject item){if(downloaders.length()==0){error("请返回下载任务，在更多中添加下载器");return;}LinearLayout f=col();f.addView(text(item.optString("name"),15,ink));Spinner d=new Spinner(this);ArrayList<String> names=new ArrayList<>();for(int i=0;i<downloaders.length();i++)names.add(downloaders.optJSONObject(i).optString("name"));d.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));f.addView(d);EditText save=input(f,"保存目录（留空使用默认值）","",false);CheckBox paused=new CheckBox(this);paused.setText("添加后暂停");f.addView(paused);dialog("添加站点种子",f,"下载",()->{try{JSONObject payload=json("downloader_id",downloaders.getJSONObject(d.getSelectedItemPosition()).getString("id"),"paused",paused.isChecked());if(!value(save).isEmpty())payload.put("save_path",value(save));mutate(path+"/download",payload);}catch(Exception e){error(e.getMessage());}});}
}











