'use strict';
const $ = (s, root=document) => root.querySelector(s);
const state = {downloaders:[],tasks:[],filter:'all',limit:50,query:'',setup:false,busy:false,epoch:0};
const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bytes = n => {n=Number(n)||0;const units=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<4){n/=1024;i++;}return `${n.toFixed(i?1:0)} ${units[i]}`;};
const date = n => n ? new Date(Number(n)*1000).toLocaleString('zh-CN') : '—';
const uuid = () => crypto.randomUUID ? crypto.randomUUID() : 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=crypto.getRandomValues(new Uint8Array(1))[0]&15;return(c==='x'?r:(r&3)|8).toString(16);});
async function api(path,method='GET',body){let r;try{r=await fetch('/api/v1'+path,{method,credentials:'same-origin',headers:{'X-Nas-Request':'1',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});}catch(e){throw new Error('无法连接服务。请检查网络后刷新。');}let data;try{data=await r.json();}catch(e){throw new Error('服务返回了无法读取的响应。');}if(!r.ok||!data.ok){if(r.status===401 && !['/login','/setup','/me'].includes(path)){showAuth(false);}const error=new Error(data.error||`服务请求失败 (${r.status})`);error.httpStatus=r.status;error.code=data.code;throw error;}return data;}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>$('#toast').hidden=true,6000);}
function showAuth(setup){if(typeof resetAutomations==='function')resetAutomations();if(typeof resourceState!=="undefined"){resourceState.epoch++;clearTimeout(resourceState.timer);resourceState.id=null;resourceState.running=false;resourceState.items=[];}pendingScope=null;pendingOperations.clear();state.setup=setup;$('#workspace').hidden=true;$('#auth').hidden=false;$('#setupLabel').hidden=!setup;$('#setupLabel input').required=setup;$('#authIntro').textContent=setup?'使用安装时生成的初始化码，创建管理员':'登录你的下载工作台';$('#authSubmit').textContent=setup?'创建管理员':'登录';}
async function start(){try{const health=await api('/health');$('#version').textContent=health.version;if(!health.configured){showAuth(true);return;}try{await api('/me');await enter();}catch(e){showAuth(false);}}catch(e){showAuth(false);$('#authError').textContent=e.message;}}
async function enter(){const me=await api('/me');initializePending(me.username);$('#auth').hidden=true;$('#workspace').hidden=false;await loadDownloaders();await refresh();}
async function loadDownloaders(){const data=await api('/downloaders');state.downloaders=data.items;const selected=$('#downloader').value;$('#downloader').innerHTML='<option value="all">全部下载器</option>'+data.items.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('');if(data.items.some(d=>String(d.id)===selected))$('#downloader').value=selected;}
function downloaderName(id){return state.downloaders.find(d=>String(d.id)===String(id))?.name || '下载器';}
async function refresh(){const epoch=++state.epoch;$('#refresh').disabled=true;try{const params=new URLSearchParams({downloader_id:$('#downloader').value,state:state.filter,query:state.query,offset:'0',limit:String(state.limit)});params.set('limit',String(Math.min(200,state.limit)));const data=await api('/tasks?'+params);for(let offset=data.items.length;offset<state.limit&&offset<data.total;){params.set('offset',String(offset));params.set('limit',String(Math.min(200,state.limit-offset)));const next=await api('/tasks?'+params);if(!next.items.length)break;data.items.push(...next.items);offset=data.items.length;}if(epoch!==state.epoch)return;state.tasks=data.items;renderTasks();$('#downSpeed').textContent=bytes(data.summary.download_speed)+'/s';$('#upSpeed').textContent=bytes(data.summary.upload_speed)+'/s';$('#downCount').textContent=data.summary.downloading;$('#totalCount').textContent=data.summary.total;$('#listCount').textContent=`显示 ${data.items.length} / ${data.total} 个任务`;$('#loadMore').hidden=data.items.length>=data.total;$('#connection').textContent='已连接';$('#updated').textContent='同步于 '+new Date().toLocaleTimeString('zh-CN');const errors=(data.errors||[]).map(e=>`${downloaderName(e.downloader_id)}：${e.error}`).join('\n');$('#taskError').textContent=errors;$('#taskError').hidden=!errors;}catch(e){if(epoch!==state.epoch)return;$('#taskError').textContent=e.message;$('#taskError').hidden=false;$('#connection').textContent='同步失败';if(!state.tasks.length)$('#tasks').innerHTML='<div class="empty"><h3>暂时无法读取任务</h3><p>检查下载器连接，然后点击刷新。</p></div>';}finally{if(epoch===state.epoch)$('#refresh').disabled=false;}}
function renderTasks(){const labels={downloading:'下载中',completed:'已完成',paused:'已暂停',seeding:'做种中',error:'任务异常',queued:'等待中',checking:'校验中'};$('#tasks').innerHTML=state.tasks.length?state.tasks.map((t,i)=>{const progress=Math.max(0,Math.min(100,Number(t.progress)*100||0));return `<article class="task"><div class="task-icon" aria-hidden="true">${t.state==='completed'?'✓':'↓'}</div><div><button class="task-name" data-detail="${i}">${esc(t.name)}</button><div class="task-meta"><span class="status">${esc(t.state_label||labels[t.state]||t.state||'未知状态')}</span><span>${progress.toFixed(1)}%</span><span>${bytes(t.total_size)}</span><span>↓ ${bytes(t.download_speed)}/s</span><span>↑ ${bytes(t.upload_speed)}/s</span><span>${esc(downloaderName(t.downloader_id))}</span></div><progress class="progress" aria-label="下载进度" value="${progress}" max="100"></progress></div><div class="task-actions"><button data-action="${i}" data-verb="${t.state==='paused'?'resume':'pause'}">${t.state==='paused'?'继续':'暂停'}</button><button data-delete="${i}" aria-label="删除 ${esc(t.name)}">删除</button></div></article>`;}).join(''):`<div class="empty"><h3>${state.downloaders.length?'这里还没有任务':'先连接一个下载器'}</h3><p>${state.query?'没有找到匹配的任务，请调整搜索条件。':state.downloaders.length?'添加磁力链接或种子文件，开始下载。':'在设置中添加 qBittorrent 或 Transmission。'}</p></div>`;}
function dialog(title,body){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=body;if(!$('#dialog').open)$('#dialog').showModal();}
function errorInDialog(message){let p=$('#modalError');if(!p){p=document.createElement('p');p.id='modalError';p.className='error';p.setAttribute('role','alert');$('#dialogBody').append(p);}p.textContent=message;}
const pendingOperations=new Map();
let pendingScope=null;
const storageError='无法持久保存操作回执。请允许本站使用本地存储后重新登录；本次操作未提交。';
function initializePending(username){pendingOperations.clear();pendingScope=null;if(typeof username!=='string'||!username)throw new Error('无法确认当前账号，下载操作已停用。');const key='nas-pending-operations:v2:'+JSON.stringify([location.origin,username]);try{const raw=localStorage.getItem(key);const entries=raw?JSON.parse(raw):[];if(!Array.isArray(entries)||entries.some(e=>!Array.isArray(e)||e.length!==2||typeof e[0]!=='string'||typeof e[1]!=='string'))throw new Error('invalid receipts');for(const entry of entries)pendingOperations.set(...entry);pendingScope=key;}catch(e){throw new Error(storageError);}}
function savePending(){if(!pendingScope)throw new Error(storageError);const value=JSON.stringify([...pendingOperations]);try{localStorage.setItem(pendingScope,value);if(localStorage.getItem(pendingScope)!==value)throw new Error('storage verification failed');}catch(e){throw new Error(storageError);}}
function clearPending(signature){const id=pendingOperations.get(signature);pendingOperations.delete(signature);try{savePending();}catch(e){if(id)pendingOperations.set(signature,id);throw new Error('操作已被确认，但本地回执清理失败。请保留记录，重复操作将继续查询原回执。');}}
async function operation(path,payload,button){if(state.busy)return;const {request_id,...content}=payload;const signature=JSON.stringify([path,content]);if(pendingOperations.has(signature)){const previous=pendingOperations.get(signature);receipt(previous,'此操作已有待确认回执，正在查询原请求。');pollOperation(previous);return;}state.busy=true;button.disabled=true;const id=request_id;pendingOperations.set(signature,id);try{savePending();}catch(e){pendingOperations.delete(signature);state.busy=false;button.disabled=false;errorInDialog(e.message);toast(e.message);return;}try{const data=await api(path,'POST',payload);if(data.operation.status==='uncertain'){receipt(id,data.operation.message);pollOperation(id);}else{clearPending(signature);toast(data.operation.message||'操作已完成');$('#dialog').close();await refresh();}}catch(e){if(e.httpStatus&&e.httpStatus<500){try{clearPending(signature);}catch(storageFailure){toast(storageFailure.message);}errorInDialog(e.message);toast(e.message);}else{receipt(id,`请求结果尚未确认：${e.message}`);pollOperation(id);}}finally{state.busy=false;button.disabled=false;}}
function receipt(id,message){dialog('操作回执',`<p>${esc(message)}</p><p class="note">正在只读查询操作状态。请勿重复提交此操作。</p><p class="note">回执编号：${esc(id)}</p><div id="receiptStatus"></div><button id="checkReceipt">查询状态</button>`);$('#checkReceipt').onclick=()=>pollOperation(id);}
async function pollOperation(id,attempt=0){try{const data=await api('/operations/'+encodeURIComponent(id));if(data.operation.status==='completed'){for(const [key,value] of pendingOperations){if(value===id)clearPending(key);}toast(data.operation.message||'操作已确认');if($('#receiptStatus'))$('#receiptStatus').textContent='操作已确认完成';await refresh();return;}if($('#receiptStatus'))$('#receiptStatus').textContent=data.operation.message||'结果待确认';if(attempt<5)setTimeout(()=>pollOperation(id,attempt+1),4000);}catch(e){if($('#receiptStatus'))$('#receiptStatus').textContent=e.message+' 可稍后在操作记录中查询。';}}
function addDialog(){if(!state.downloaders.length){settings('downloaders');return;}dialog('添加下载任务',`<form id="addForm" class="form-grid"><label>下载器<select name="downloader_id">${state.downloaders.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('')}</select></label><label>磁力链接或种子地址<input name="url" placeholder="magnet:?xt=… 或 https://…" autocomplete="off"></label><label>或者选择种子文件<input name="torrent" type="file" accept=".torrent"></label><label>保存路径（留空使用下载器默认路径）<input name="save_path" placeholder="/downloads"></label><label class="check"><input name="paused" type="checkbox">添加后暂停</label><p id="modalError" class="error" role="alert"></p><button class="primary" type="submit">添加任务</button></form>`);const request_id=uuid();$('#addForm').onsubmit=async e=>{e.preventDefault();const form=e.target;const values=Object.fromEntries(new FormData(form));const file=form.elements.torrent.files[0];if((!!values.url.trim())===!!file){errorInDialog('请填写链接或选择种子文件，两者选一。');return;}const body={request_id,downloader_id:values.downloader_id,paused:form.elements.paused.checked,save_path:values.save_path};if(file){if(file.size>2*1024*1024){errorInDialog('种子文件不能超过 2 MB。');return;}body.name=file.name;body.torrent_base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(new Error('无法读取种子文件'));reader.readAsDataURL(file);});}else body.url=values.url.trim();await operation('/tasks/add',body,form.querySelector('button[type=submit]'));};}
function taskPath(t){return '/tasks/'+encodeURIComponent(t.downloader_id)+'/'+encodeURIComponent(t.id);}
async function action(t,verb,button,delete_data=false){await operation(taskPath(t)+'/action',{request_id:uuid(),action:verb,delete_data},button);}
function deleteDialog(t){dialog('删除下载任务',`<p>删除「${esc(t.name)}」？</p><p class="note">默认只移除任务，保留已经下载的文件。</p><label class="check"><input id="deleteData" type="checkbox">同时永久删除已下载文件</label><div class="buttons"><button id="confirmDelete" class="danger">删除任务</button><button id="cancelDelete">取消</button></div>`);$('#cancelDelete').onclick=()=>$('#dialog').close();$('#confirmDelete').onclick=e=>action(t,'delete',e.target,$('#deleteData').checked);}
async function detail(t){dialog('任务详情','<p class="note">正在读取文件与 Tracker…</p>');try{const d=await api(taskPath(t));$('#dialogBody').innerHTML=`<h3>${esc(d.item.name)}</h3><div class="detail-line"><span>大小</span><span>${bytes(d.item.total_size)}</span></div><div class="detail-line"><span>保存路径</span><span>${esc(d.item.save_path||'未提供')}</span></div><h3>文件 (${d.files.length})</h3>${d.files.map(f=>`<div class="item">${esc(f.name)}<p>${bytes(f.size)}　${(Number(f.progress)*100).toFixed(1)}%</p></div>`).join('')||'<p class="note">下载器尚未提供文件列表。</p>'}<h3 class="detail-section">Tracker (${d.trackers.length})</h3>${d.trackers.map(tr=>`<div class="item">${esc(tr.url)}<p>${esc(tr.status)}　${esc(tr.message)}</p></div>`).join('')||'<p class="note">没有 Tracker 信息。</p>'}`;}catch(e){errorInDialog(e.message);}}
async function settings(section='downloaders'){dialog('设置',`<nav class="section-nav"><button data-settings="downloaders">下载器</button><button data-settings="pair">手机配对</button><button data-settings="devices">登录设备</button><button data-settings="history">操作记录</button></nav><div id="settingsContent"><p class="note">正在读取…</p></div>`);const root=$('#settingsContent');try{if(section==='downloaders'){await loadDownloaders();root.innerHTML=`<button id="newDownloader" class="primary">＋ 连接下载器</button>${state.downloaders.map((d,i)=>`<div class="item"><h3>${esc(d.name)}</h3><p>${esc(d.type)}　${esc(d.url)}</p><p>默认路径：${esc(d.default_save_path||'下载器默认')}</p><div class="buttons"><button data-edit="${i}">编辑连接</button><button data-remove="${i}" class="danger">移除接入</button></div></div>`).join('')||'<p class="note">连接下载器后，这里会显示连接信息。</p>'}`;$('#newDownloader').onclick=()=>downloaderForm();}else if(section==='pair'){root.innerHTML='<p>用五分钟内有效的一次性配对码，连接手机应用。</p><label class="detail-section">设备名称<input id="pairLabel" value="我的手机" maxlength="80"></label><div class="buttons"><button id="makePair" class="primary">生成配对码</button></div><div id="pairResult"></div>';$('#makePair').onclick=async e=>{e.target.disabled=true;try{const d=await api('/pair-codes','POST',{label:$('#pairLabel').value});$('#pairResult').innerHTML=`<div class="pair-code">${esc(d.code)}</div><p class="note">到期时间：${esc(date(d.expires_at))}。请在手机应用中输入。</p>`;}catch(err){errorInDialog(err.message);}finally{e.target.disabled=false;}};}else if(section==='devices'){const d=await api('/devices');root.innerHTML=d.items.map(device=>`<div class="item"><h3>${esc(device.label||'登录设备')}${device.current?'（当前设备）':''}</h3><p>创建：${esc(date(device.created_at))}<br>最近访问：${esc(date(device.last_seen))}</p><div class="buttons"><button data-revoke="${esc(device.id)}" data-current="${device.current?'1':'0'}" class="danger">撤销登录</button></div></div>`).join('')||'<p class="note">没有登录设备。</p>';}else{const d=await api('/history?limit=50');root.innerHTML=d.items.map(o=>`<div class="item"><h3>${esc(o.action||o.type||'下载操作')} · ${esc(o.status)}</h3><p>${esc(o.message)}<br>${esc(o.request_id)}</p>${o.status==='uncertain'?`<button data-operation="${esc(o.request_id)}">查询状态</button>`:''}</div>`).join('')||'<p class="note">还没有操作记录。</p>';}}catch(e){errorInDialog(e.message);}}
function downloaderForm(d){dialog(d?'编辑下载器':'连接下载器',`<form id="downloaderForm" class="form-grid"><label>名称<input name="name" required value="${esc(d?.name||'')}"></label><label>类型<select name="type"><option value="qbittorrent">qBittorrent</option><option value="transmission" ${d?.type==='transmission'?'selected':''}>Transmission</option></select></label><label>Web 地址<input name="url" type="url" required placeholder="http://192.168.1.10:8080" value="${esc(d?.url||'')}"></label><div class="form-row"><label>用户名<input name="username" autocomplete="off" value="${esc(d?.username||'')}"></label><label>${d?'新密码（留空保留）':'密码'}<input name="password" type="password" autocomplete="new-password"></label></div><label>默认保存路径<input name="default_save_path" value="${esc(d?.default_save_path||'')}" placeholder="/downloads"></label><p id="modalError" class="error" role="alert"></p><div class="buttons"><button id="testDownloader" type="button">测试连接</button><button type="submit" class="primary">验证并保存</button></div></form>`);const form=$('#downloaderForm');const values=()=>{const v=Object.fromEntries(new FormData(form));if(d&&!v.password)delete v.password;if(d&&!v.username)delete v.username;return v;};$('#testDownloader').onclick=async e=>{e.target.disabled=true;try{const v=values();if(d&&!v.password){errorInDialog('测试连接需要输入密码；保存时留空可保留原密码。');return;}const result=await api('/downloaders/test','POST',v);toast('连接成功 · '+result.version);}catch(err){errorInDialog(err.message);}finally{e.target.disabled=false;}};form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;try{await api('/downloaders'+(d?'/'+encodeURIComponent(d.id):''),d?'PATCH':'POST',values());toast('下载器已保存');await settings();await refresh();}catch(err){errorInDialog(err.message);}finally{button.disabled=false;}};}
$('#authForm').onsubmit=async e=>{e.preventDefault();$('#authSubmit').disabled=true;$('#authError').textContent='';try{await api(state.setup?'/setup':'/login','POST',Object.fromEntries(new FormData(e.target)));e.target.reset();await enter();}catch(err){$('#authError').textContent=err.message;}finally{$('#authSubmit').disabled=false;}};
$('#logout').onclick=async()=>{try{await api('/logout','POST',{});$('#dialog').close();showAuth(false);}catch(e){toast(e.message);}};
$('#add').onclick=addDialog;$('#settings').onclick=()=>settings();$('#refresh').onclick=refresh;$('#downloader').onchange=()=>{state.limit=50;refresh();};$('#loadMore').onclick=()=>{state.limit+=50;refresh();};$('#closeDialog').onclick=()=>$('#dialog').close();
$('#tabs').onclick=e=>{const b=e.target.closest('[data-state]');if(!b)return;state.filter=b.dataset.state;state.limit=50;for(const tab of $('#tabs').children){const active=tab===b;tab.classList.toggle('active',active);tab.setAttribute('aria-pressed',String(active));}refresh();};
let searchTimer;$('#search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.query=$('#search').value.trim();state.limit=50;refresh();},300);};$('#clearSearch').onclick=()=>{clearTimeout(searchTimer);$('#search').value='';state.query='';state.limit=50;refresh();};
$('#tasks').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.detail!==undefined)detail(state.tasks[Number(b.dataset.detail)]);if(b.dataset.action!==undefined)action(state.tasks[Number(b.dataset.action)],b.dataset.verb,b);if(b.dataset.delete!==undefined)deleteDialog(state.tasks[Number(b.dataset.delete)]);};
$('#dialogBody').onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.settings)settings(b.dataset.settings);if(b.dataset.edit!==undefined)downloaderForm(state.downloaders[Number(b.dataset.edit)]);if(b.dataset.remove!==undefined){const d=state.downloaders[Number(b.dataset.remove)];dialog('移除下载器接入',`<p>移除「${esc(d.name)}」的连接？下载器内的任务会保留。</p><div class="buttons"><button id="confirmRemove" class="danger">移除接入</button></div>`);$('#confirmRemove').onclick=async e=>{e.target.disabled=true;try{await api('/downloaders/'+encodeURIComponent(d.id),'DELETE');await settings();await refresh();}catch(err){errorInDialog(err.message);e.target.disabled=false;}};}if(b.dataset.revoke){if(!confirm('撤销此设备的登录？该设备需要重新登录。'))return;try{await api('/devices/'+encodeURIComponent(b.dataset.revoke),'DELETE');if(b.dataset.current==='1'){ $('#dialog').close();showAuth(false);}else settings('devices');}catch(err){errorInDialog(err.message);}}if(b.dataset.operation){receipt(b.dataset.operation,'正在查询操作状态');pollOperation(b.dataset.operation);}};
setInterval(()=>{if(!document.hidden&&!$('#workspace').hidden&&!$('#downloadView').hidden&&!state.busy)refresh();},10000);
start();

// Independent site search shares the durable operation receipt flow above.
const resourceState={sites:[],items:[],epoch:0,id:null,timer:null,running:false,page:1,query:'',siteIds:[],totals:{}};
function resourceView(open){if(typeof leaveAutomations==='function')leaveAutomations();$('#downloadView').hidden=open;$('#resourceView').hidden=!open;$('#viewDownloads').setAttribute('aria-pressed',String(!open));$('#viewResources').setAttribute('aria-pressed',String(open));if(open)loadSites().catch(e=>toast(e.message));}
async function loadSites(){const d=await api('/sites');resourceState.sites=d.items;$('#resourceSites').innerHTML=d.items.filter(s=>s.enabled).map(s=>`<label class="check"><input type="checkbox" value="${esc(s.id)}" checked>${esc(s.name)}</label>`).join('')||'<p class="note">请先配置并启用一个站点。</p>';}
async function siteSettings(){dialog('站点配置','<div id="siteList">正在读取…</div>');try{const d=await api('/sites');resourceState.sites=d.items;$('#siteList').innerHTML='<p class="note">自行配置 M-Team 或 Torznab；不会导入旧凭据。保存配置后，主动搜索验证连接。</p><button id="newSite" class="primary">＋ 添加站点</button>'+d.items.map((s,i)=>`<div class="item"><h3>${esc(s.name)} · ${s.enabled?'已启用':'已停用'}</h3><p>${esc(s.type)} · ${s.has_api_key?'已设置密钥':'未设置密钥'}</p><div class="buttons"><button data-site-edit="${i}">编辑</button><button data-site-delete="${i}" class="danger">移除</button></div></div>`).join('');$('#newSite').onclick=()=>siteForm();}catch(e){errorInDialog(e.message);}}
function siteForm(s){dialog(s?'编辑站点':'添加站点',`<form id="siteForm" class="form-grid"><label>名称<input name="name" required maxlength="80" value="${esc(s?.name||'')}"></label><label>类型<select name="type"><option value="mteam">M-Team</option><option value="torznab" ${s?.type==='torznab'?'selected':''}>Torznab（Jackett / Prowlarr）</option></select></label><label>API 地址<input name="url" type="url" required value="${esc(s?.url||'https://api.m-team.cc/api')}"></label><p class="note">M-Team 使用官方 API 地址；Torznab 填完整 API 路径，地址中不能包含密钥、查询参数或账号密码。</p><label>${s?'API 密钥（留空保留）':'API 密钥'}<input name="api_key" type="password" autocomplete="new-password"></label><label class="check"><input name="enabled" type="checkbox" ${s?.enabled!==false?'checked':''}>启用站点</label><p id="modalError" class="error" role="alert"></p><button type="submit" class="primary">保存配置</button></form>`);$('#siteForm').onsubmit=async e=>{e.preventDefault();const f=e.target,b=f.querySelector('[type=submit]');b.disabled=true;try{const v=Object.fromEntries(new FormData(f));v.enabled=f.elements.enabled.checked;if(s&&!v.api_key)delete v.api_key;await api('/sites'+(s?'/'+encodeURIComponent(s.id):''),s?'PATCH':'POST',v);await loadSites();await siteSettings();}catch(err){errorInDialog(err.message);}finally{b.disabled=false;}};}
async function stopResources(){const old=resourceState.id;++resourceState.epoch;clearTimeout(resourceState.timer);resourceState.id=null;resourceState.running=false;$('#stopResources').disabled=true;$('#searchResources').disabled=false;$('#resourceMore').hidden=true;$('#resourceStatus').textContent='搜索已停止，已获取结果保留。';if(old)try{await api('/searches/'+encodeURIComponent(old),'DELETE');}catch(e){toast('已停止本地搜索；服务端取消未确认：'+e.message);}}
async function searchResources(more=false){const old=resourceState.id,epoch=++resourceState.epoch;clearTimeout(resourceState.timer);resourceState.id=null;if(old)try{await api('/searches/'+encodeURIComponent(old),'DELETE');}catch(e){if(epoch!==resourceState.epoch)return;toast('旧搜索取消未确认：'+e.message);}if(epoch!==resourceState.epoch)return;if(!more){resourceState.query=$('#resourceQuery').value.trim();resourceState.siteIds=Array.from($('#resourceSites').querySelectorAll('input:checked'),i=>i.value);resourceState.items=[];resourceState.page=1;resourceState.totals={};}else resourceState.page++;if(!resourceState.query||!resourceState.siteIds.length){$('#resourceStatus').textContent='请输入关键词，并选择至少一个已启用站点。';return;}resourceState.running=true;$('#searchResources').disabled=false;$('#stopResources').disabled=false;$('#resourceMore').hidden=true;$('#resourceError').textContent='';$('#resourceStatus').textContent='正在搜索…';renderResources();try{const d=await api('/searches','POST',{query:resourceState.query,site_ids:resourceState.siteIds,page:resourceState.page,limit:30});if(epoch!==resourceState.epoch){api('/searches/'+encodeURIComponent(d.search_id),'DELETE').catch(()=>{});return;}resourceState.id=d.search_id;await pollResources(epoch);}catch(e){if(epoch!==resourceState.epoch)return;resourceState.running=false;$('#stopResources').disabled=true;$('#resourceError').textContent=e.message;$('#resourceStatus').textContent='搜索失败，请修改条件后重试。';}}
async function pollResources(epoch){const id=resourceState.id;if(epoch!==resourceState.epoch||!id)return;try{let offset=0,data,received=[];do{data=await api('/searches/'+encodeURIComponent(id)+'?offset='+offset+'&limit=100');if(epoch!==resourceState.epoch)return;received.push(...data.items);offset+=data.items.length;}while(offset<data.total&&data.items.length);const known=new Set(resourceState.items.map(i=>JSON.stringify([i.site_id,i.id])));for(const item of received){const key=JSON.stringify([item.site_id,item.id]);if(!known.has(key)){known.add(key);resourceState.items.push(item);}}resourceState.totals=data.site_totals||{};$('#resourceError').textContent=(data.errors||[]).map(e=>`${resourceState.sites.find(s=>String(s.id)===String(e.site_id))?.name||'站点'}：${e.error||e.code}`).join('\n');resourceState.running=data.status==='running';renderResources();$('#resourceStatus').textContent=`${resourceState.running?'正在搜索':'搜索'+(data.status==='cancelled'?'已停止':'完成')} · 已获取 ${resourceState.items.length} 条 · 总大小 ${bytes(resourceState.items.reduce((n,i)=>n+(Number(i.size)||0),0))}`;$('#stopResources').disabled=!resourceState.running;$('#resourceMore').hidden=resourceState.running||data.status==='cancelled'||!Object.values(resourceState.totals).some(n=>Number(n)>resourceState.page*30);if(resourceState.running)resourceState.timer=setTimeout(()=>pollResources(epoch),1500);}catch(e){if(epoch!==resourceState.epoch)return;resourceState.running=false;$('#stopResources').disabled=true;$('#resourceError').textContent=e.message;$('#resourceStatus').textContent='读取搜索失败；已获取结果保留，可重新搜索。';}}
function renderResources(){$('#resourceResults').innerHTML=resourceState.items.length?resourceState.items.map((i,n)=>`<article class="resource-item"><div><button class="task-name" data-resource-detail="${n}">${esc(i.name)}</button><p class="note">${esc(i.subtitle||'')}</p><div class="task-meta"><span class="site-badge">${esc(i.site_name)}</span><span class="promotion-badge">${esc(i.promotion||'普通')}</span><span>${bytes(i.size)}</span><span>做种 ${esc(i.seeders??'—')} · 下载 ${esc(i.leechers??'—')}</span></div></div><button data-resource-download="${n}">下载</button></article>`).join(''):`<div class="empty"><h3>${resourceState.running?'正在收集站点结果…':'暂无资源结果'}</h3><p>调整上方关键词或站点，再次搜索。</p><button id="returnResourceSearch">返回搜索</button></div>`;const back=$('#returnResourceSearch');if(back)back.onclick=()=>$('#resourceQuery').focus();}
async function resourceDetail(i){const epoch=resourceState.epoch;dialog('资源详情','<p class="note">正在读取…</p>');try{const d=await api('/sites/'+encodeURIComponent(i.site_id)+'/torrents/'+encodeURIComponent(i.id));if(epoch!==resourceState.epoch||!$('#dialog').open)return;$('#dialogBody').innerHTML=`<h3>${esc(d.item.name)}</h3><p class="note">${esc(i.site_name)} · ${bytes(d.item.size)} · ${esc(d.item.promotion||'普通')}</p><pre id="resourceDescription" class="resource-description"></pre><button id="detailDownload" class="primary">选择下载器下载</button>`;$('#resourceDescription').textContent=d.item.description||d.item.subtitle||'站点未提供描述。';$('#detailDownload').onclick=()=>resourceDownload(i);}catch(e){errorInDialog(e.message);}}
function resourceDownload(i){if(!state.downloaders.length){settings();return;}dialog('下载资源',`<h3>${esc(i.name)}</h3><p class="note">${esc(i.site_name)} · ${bytes(i.size)} · ${esc(i.promotion||'普通')}</p><form id="resourceDownloadForm" class="form-grid"><label>下载器<select name="downloader_id">${state.downloaders.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('')}</select></label><label>保存路径（留空使用默认路径）<input name="save_path"></label><label class="check"><input name="paused" type="checkbox">添加后暂停</label><p id="modalError" class="error" role="alert"></p><button type="submit" class="primary">添加下载任务</button></form>`);const request_id=uuid();$('#resourceDownloadForm').onsubmit=async e=>{e.preventDefault();const f=e.target,v=Object.fromEntries(new FormData(f));v.paused=f.elements.paused.checked;await operation('/sites/'+encodeURIComponent(i.site_id)+'/torrents/'+encodeURIComponent(i.id)+'/download',{request_id,...v},f.querySelector('[type=submit]'));};}
$('#viewDownloads').onclick=()=>resourceView(false);$('#viewResources').onclick=()=>resourceView(true);$('#manageSites').onclick=siteSettings;$('#resourceSearchForm').onsubmit=e=>{e.preventDefault();searchResources();};$('#stopResources').onclick=stopResources;$('#resourceMore').onclick=()=>searchResources(true);$('#resourceResults').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.resourceDetail!==undefined)resourceDetail(resourceState.items[Number(b.dataset.resourceDetail)]);if(b.dataset.resourceDownload!==undefined)resourceDownload(resourceState.items[Number(b.dataset.resourceDownload)]);};
$('#dialogBody').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.siteEdit!==undefined)siteForm(resourceState.sites[Number(b.dataset.siteEdit)]);if(b.dataset.siteDelete!==undefined){const s=resourceState.sites[Number(b.dataset.siteDelete)];dialog('移除站点',`<p>移除「${esc(s.name)}」的接入配置？</p><button id="removeSite" class="danger">移除配置</button>`);$('#removeSite').onclick=async e=>{e.target.disabled=true;try{await api('/sites/'+encodeURIComponent(s.id),'DELETE');await loadSites();await siteSettings();}catch(err){errorInDialog(err.message);e.target.disabled=false;}};}});

