'use strict';
// The browser observes NAS jobs; leaving this view never cancels their schedule.
const automationState = {items:[],sites:[],filter:'all',active:false,epoch:0,listRequest:0,timer:null,dialogEpoch:0,runTimer:null,scope:null,createScope:null,pending:new Map(),creates:new Map(),busy:new Set()};
const automationKinds = {http_signin:'自定义站点签到',hdfans_signin:'HDFans 签到',mteam_check:'M-Team 账户检查（非网页登录保号）',brush:'自动刷流'};
const automationStatuses = {queued:'等待执行',running:'执行中',completed:'已完成',failed:'执行失败',cancelled:'已停止',interrupted:'执行中断，需核查',needs_review:'结果待核查',idle:'尚未执行',success:'成功',already_signed:'今日已签到',cookie_invalid:'Cookie 已失效',auth_failure:'Cookie 已失效',uncertain:'结果待核查',preview:'预演完成',account_checked:'账户检查完成',already_attempted:'今日已尝试',active:'管理中',removed:'已移除',challenge:'需要人工验证',unknown:'结果待核查',stopped:'已停止'};
const automationPath = id => '/automations/'+encodeURIComponent(id);
const automationStatus = status => automationStatuses[status] || status || '尚未执行';
const automationDate = n => n ? new Date(Number(n)*1000).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}) : '—';
const automationFinished = status => ['completed','failed','cancelled'].includes(status);
function automationError(message){$('#automationError').textContent=message;$('#automationError').hidden=!message;}
function automationModalError(message){const el=$('#automationModalError');if(el)el.textContent=message;else toast(message);}
function automationDialog(title,body){$('#automationDialogBody').onclick=null;clearTimeout(automationState.runTimer);++automationState.dialogEpoch;$('#automationDialogTitle').textContent=title;$('#automationDialogBody').innerHTML=body;if(!$('#automationDialog').open)$('#automationDialog').showModal();return automationState.dialogEpoch;}
function closeAutomationDialog(){++automationState.dialogEpoch;clearTimeout(automationState.runTimer);$('#automationDialog').close();$('#automationDialogBody').onclick=null;$('#automationDialogBody').innerHTML='';}
function leaveAutomations(){automationState.active=false;++automationState.epoch;clearTimeout(automationState.timer);closeAutomationDialog();$('#automationView').hidden=true;$('#viewAutomations').setAttribute('aria-pressed','false');}
function resetAutomations(){leaveAutomations();$('#downloadView').hidden=false;$('#resourceView').hidden=true;$('#viewDownloads').setAttribute('aria-pressed','true');$('#viewResources').setAttribute('aria-pressed','false');automationState.items=[];automationState.sites=[];automationState.pending.clear();automationState.creates.clear();automationState.scope=null;automationState.createScope=null;$('#automationList').innerHTML='';}
async function initializeAutomations(){
 const me=await api('/me');if(typeof me.username!=='string'||!me.username)throw new Error('无法确认当前账号，请重新登录。');
 const account=JSON.stringify([location.origin,me.username]),scope='nas-automation-runs:v1:'+account,createScope='nas-automation-creates:v1:'+account;
 if(automationState.scope===scope&&automationState.createScope===createScope)return;
 automationState.scope=null;automationState.createScope=null;automationState.pending.clear();automationState.creates.clear();
 try{
  const entries=JSON.parse(localStorage.getItem(scope)||'[]');if(!Array.isArray(entries))throw Error();
  for(const entry of entries){if(!Array.isArray(entry)||entry.length!==2||typeof entry[0]!=='string'||!entry[1]||typeof entry[1].request_id!=='string'||typeof entry[1].automation_id!=='string'||typeof entry[1].dry_run!=='boolean')throw Error();automationState.pending.set(entry[0],entry[1]);}
  const creates=JSON.parse(localStorage.getItem(createScope)||'[]');if(!Array.isArray(creates))throw Error();
  for(const entry of creates){if(!Array.isArray(entry)||entry.length!==2||!automationKinds[entry[0]]||typeof entry[1]?.request_id!=='string'||typeof entry[1]?.fingerprint!=='string'||!entry[1]?.body||['cookie','headers_json','request_body'].some(k=>Object.hasOwn(entry[1].body,k)))throw Error();automationState.creates.set(entry[0],entry[1]);}
  automationState.scope=scope;automationState.createScope=createScope;
 }catch(e){throw new Error('无法读取执行回执。请允许本站使用本地存储后重新登录。');}
}
function saveAutomationPending(){if(!automationState.scope)throw new Error('尚未确认当前账号，本次执行未提交。');const value=JSON.stringify([...automationState.pending]);try{localStorage.setItem(automationState.scope,value);if(localStorage.getItem(automationState.scope)!==value)throw Error();}catch(e){throw new Error('无法保存执行回执，本次执行未提交。请允许本站使用本地存储。');}}
function removeAutomationPending(key){const item=automationState.pending.get(key);automationState.pending.delete(key);try{saveAutomationPending();}catch(e){if(item)automationState.pending.set(key,item);throw new Error('运行状态已确认，但本地回执未能清理。再次点击将继续查询原运行。');}}
function saveAutomationCreates(){if(!automationState.createScope)throw new Error('尚未确认当前账号，本次保存未提交。');const value=JSON.stringify([...automationState.creates]);try{localStorage.setItem(automationState.createScope,value);if(localStorage.getItem(automationState.createScope)!==value)throw Error();}catch(e){throw new Error('无法保存创建回执，本次保存未提交。请允许本站使用本地存储。');}}
function removeAutomationCreate(kind){const previous=automationState.creates.get(kind);automationState.creates.delete(kind);try{saveAutomationCreates();}catch(e){if(previous)automationState.creates.set(kind,previous);throw new Error('配置结果已确认，但本地创建回执未能清理。再次保存将继续确认原配置。');}}
// LAN HTTP pages do not expose crypto.subtle. Keep the same SHA-256 fingerprint there.
function automationSha256(input){
 const constants=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2];
 const hash=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19],data=new Uint8Array(Math.ceil((input.length+9)/64)*64);data.set(input);data[input.length]=0x80;
 const view=new DataView(data.buffer);view.setUint32(data.length-8,Math.floor(input.length/0x20000000));view.setUint32(data.length-4,(input.length*8)>>>0);const rotate=(n,b)=>(n>>>b)|(n<<(32-b)),words=new Uint32Array(64);
 for(let offset=0;offset<data.length;offset+=64){
  for(let i=0;i<16;i++)words[i]=view.getUint32(offset+i*4);
  for(let i=16;i<64;i++){const x=words[i-15],y=words[i-2],s0=rotate(x,7)^rotate(x,18)^(x>>>3),s1=rotate(y,17)^rotate(y,19)^(y>>>10);words[i]=(words[i-16]+s0+words[i-7]+s1)>>>0;}
  let [a,b,c,d,e,f,g,h]=hash;
  for(let i=0;i<64;i++){const s1=rotate(e,6)^rotate(e,11)^rotate(e,25),choose=(e&f)^(~e&g),t1=(h+s1+choose+constants[i]+words[i])>>>0,s0=rotate(a,2)^rotate(a,13)^rotate(a,22),majority=(a&b)^(a&c)^(b&c),t2=(s0+majority)>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0;}
  for(const [i,value] of [a,b,c,d,e,f,g,h].entries())hash[i]=(hash[i]+value)>>>0;
 }
 return hash.map(n=>n.toString(16).padStart(8,'0')).join('');
}
async function automationFingerprint(body){const canonical=JSON.stringify(Object.keys(body).sort().map(k=>[k,body[k]])),encoded=new TextEncoder().encode(canonical);if(!crypto.subtle)return automationSha256(encoded);const hash=await crypto.subtle.digest('SHA-256',encoded);return Array.from(new Uint8Array(hash),n=>n.toString(16).padStart(2,'0')).join('');}
async function createAutomationConfig(body){
 const kind=body.kind,scope=automationState.createScope;const fingerprint=await automationFingerprint(body);if(scope!==automationState.createScope)throw new Error('登录状态已变化，本次保存未提交。');let receipt=automationState.creates.get(kind);
 if(receipt&&receipt.fingerprint!==fingerprint)throw new Error('此前创建结果尚未确认。请保持原设置'+(kind==='hdfans_signin'?'并重填相同 Cookie':'')+'后重试，或先在列表核查原配置。');
 if(!receipt){const safeBody={...body};for(const key of ["cookie","headers_json","request_body"])delete safeBody[key];receipt={request_id:uuid(),fingerprint,body:safeBody};automationState.creates.set(kind,receipt);try{saveAutomationCreates();}catch(e){automationState.creates.delete(kind);throw e;}}
 try{const result=await api('/automations','POST',{...body,request_id:receipt.request_id});if(scope===automationState.createScope)removeAutomationCreate(kind);return result;}
 catch(e){if(scope===automationState.createScope&&e.httpStatus&&e.httpStatus<500&&e.httpStatus!==409){try{removeAutomationCreate(kind);}catch(cleanup){toast(cleanup.message);}}throw e;}
}
function acknowledgeAutomationCreate(kind){automationDialog('核查未确认的创建',`<p>先在任务列表核实原配置是否已经创建，再关闭这条本地回执。</p><p class="note">只清除浏览器的创建回执，不删除、不停用 NAS 中的配置，也不会提交新任务。</p><p id="automationModalError" class="error" role="alert"></p><div class="buttons"><button id="ackAutomationCreate">已核查列表，关闭本地回执</button><button id="cancelAckAutomationCreate">返回</button></div>`);$('#cancelAckAutomationCreate').onclick=()=>automationForm({kind,enabled:false});$('#ackAutomationCreate').onclick=()=>{try{removeAutomationCreate(kind);closeAutomationDialog();toast('本地创建回执已关闭，NAS 配置保留');}catch(e){automationModalError(e.message);}};}

async function openAutomations(){resourceView(false);$('#downloadView').hidden=true;$('#resourceView').hidden=true;$('#automationView').hidden=false;$('#viewDownloads').setAttribute('aria-pressed','false');$('#viewResources').setAttribute('aria-pressed','false');$('#viewAutomations').setAttribute('aria-pressed','true');automationState.active=true;const epoch=++automationState.epoch;automationError('');try{await initializeAutomations();if(epoch!==automationState.epoch)return;await refreshAutomations(epoch);}catch(e){if(epoch===automationState.epoch)automationError(e.message);}}
async function refreshAutomations(epoch=automationState.epoch){if(!automationState.active||epoch!==automationState.epoch)return;const request=++automationState.listRequest;clearTimeout(automationState.timer);$('#refreshAutomations').disabled=true;try{const data=await api('/automations');if(epoch!==automationState.epoch||request!==automationState.listRequest)return;automationState.items=data.items;automationError('');renderAutomations();}catch(e){if(epoch===automationState.epoch&&request===automationState.listRequest)automationError(e.message);}finally{if(epoch===automationState.epoch&&request===automationState.listRequest&&automationState.active){$('#refreshAutomations').disabled=false;automationState.timer=setTimeout(()=>refreshAutomations(epoch),10000);}}}
function renderAutomations(){const items=automationState.items.filter(a=>automationState.filter==='all'||(automationState.filter==='brush'?a.kind==='brush':a.kind!=='brush'));$('#automationCount').textContent=`${items.length} 个任务`;$('#automationList').innerHTML=items.length?items.map(a=>{const id=esc(a.id);const busy=automationState.busy.has(String(a.id));return `<article class="automation-item"><div class="automation-main"><div class="automation-title"><h3>${esc(a.name||automationKinds[a.kind])}</h3><button class="automation-toggle" role="switch" aria-checked="${!!a.enabled}" aria-label="${a.enabled?'停用':'启用'} ${esc(a.name)}" data-auto-action="toggle" data-auto-id="${id}" ${busy?'disabled':''}>${a.enabled?'已启用':'已停用'}</button></div><p class="note automation-kind">${esc(automationKinds[a.kind]||a.kind)}${a.kind==='hdfans_signin'?' · '+(a.has_cookie?'已保存 Cookie':'未设置 Cookie'):''}</p><dl class="automation-facts"><div><dt>下次执行（北京时间）</dt><dd>${a.enabled?esc(automationDate(a.next_run)):'启用后排期'}</dd></div><div><dt>最近执行</dt><dd>${a.last_run_dry_run===true?'预演 · ':a.last_run_dry_run===false?'真实执行 · ':''}${esc(automationStatus(a.last_status))}${a.last_run_at?'<br><span class="automation-last-time">'+esc(automationDate(a.last_run_at))+'</span>':''}</dd></div><div><dt>计划</dt><dd>${a.kind==='brush'?`每 ${esc(a.interval_minutes)} 分钟`:`${esc(a.window_start)}–${esc(a.window_end)} · 北京时间随机`}</dd></div></dl></div><div class="automation-actions"><button data-auto-action="edit" data-auto-id="${id}">编辑</button><button data-auto-action="preview" data-auto-id="${id}">预演</button><button data-auto-action="run" data-auto-id="${id}">执行</button><button data-auto-action="stop" data-auto-id="${id}" ${busy?'disabled':''}>停止并停用</button><button data-auto-action="logs" data-auto-id="${id}">日志</button>${a.kind==='brush'?`<button data-auto-action="protections" data-auto-id="${id}">保护名单</button>`:''}<button class="danger" data-auto-action="delete" data-auto-id="${id}">删除配置</button></div></article>`;}).join(''):'<div class="empty"><h3>还没有这类自动化任务</h3><p>新建签到、账户检查或刷流任务，先预演，再按需启用。</p></div>';}
function newAutomation(){automationDialog('新建自动化任务',`<p class="note">选择任务类型。保存后默认停用，可先预演配置。</p><div class="automation-type-list"><button data-auto-kind="http_signin"><strong>自定义站点签到</strong><span>自行设置地址、认证、请求方式及成功标志</span></button><button data-auto-kind="hdfans_signin"><strong>HDFans 签到</strong><span>每天在指定的北京时间窗口随机执行</span></button><button data-auto-kind="mteam_check"><strong>M-Team 账户检查</strong><span>检查连接与 VIP 到期时间，非网页登录保号</span></button><button data-auto-kind="brush"><strong>自动刷流</strong><span>按容量、人数和保护规则筛选资源</span></button></div>`);}
function automationNumber(name,label,value,min,max,step=1){return `<label>${label}<input type="number" name="${name}" value="${esc(value)}" min="${min}" max="${max}" step="${step}" required></label>`;}
function automationOptions(items,value){return items.map(i=>`<option value="${esc(i.id)}" ${String(i.id)===String(value)?'selected':''}>${esc(i.name)}${i.enabled===false?'（站点已停用）':''}</option>`).join('');}
async function automationForm(input){const pendingCreate=!input.id&&automationState.creates.get(input.kind);if(pendingCreate)input={...pendingCreate.body};const token=automationDialog(input.id?'编辑自动化任务':'新建'+automationKinds[input.kind],'<p class="note">正在读取配置…</p>');try{const reads=[api('/sites'),api('/downloaders')];if(input.id)reads.push(api(automationPath(input.id)));const results=await Promise.all(reads);if(token!==automationState.dialogEpoch||!$('#automationDialog').open)return;automationState.sites=results[0].items;const downloaders=results[1].items,a=results[2]?.item||input;const kind=a.kind,isBrush=kind==='brush';const sites=automationState.sites.filter(s=>kind==='mteam_check'?s.type==='mteam':['mteam','torznab'].includes(s.type));const selectedSite=sites.some(s=>String(s.id)===String(a.site_id))?a.site_id:sites[0]?.id;const selectedDownloader=downloaders.some(d=>String(d.id)===String(a.downloader_id))?a.downloader_id:downloaders[0]?.id;let fields=`<label>任务名称<input name="name" required maxlength="80" value="${esc(a.name||automationKinds[kind])}"></label><p class="note">${esc(automationKinds[kind])}</p>`;
if(kind==='hdfans_signin')fields+=`<label>${a.has_cookie?'更新 Cookie（留空保留）':'HDFans Cookie'}<input type="password" name="cookie" autocomplete="new-password" ${a.has_cookie?'':'required'}></label><p class="note">Cookie 只提交给你的 NAS，保存后不回显。每日最多一次真实尝试；失效或需要验证码时请到站点手动处理。</p>`;
if(!['hdfans_signin','http_signin'].includes(kind))fields+=`<label>站点<select name="site_id" required><option value="">请选择站点</option>${automationOptions(sites,selectedSite)}</select></label>${sites.length?'':'<p class="note">请先到“资源搜索 → 配置站点”添加相应站点。</p>'}`;
if(kind==='http_signin')fields+=`<label>签到地址（认证信息请放请求头或正文）<input name="signin_url" type="url" required value="${esc(a.signin_url||'')}" placeholder="https://example.com/api/checkin"></label><div class="form-row"><label>请求方式<select name="method"><option value="GET" ${a.method!=='POST'?'selected':''}>GET</option><option value="POST" ${a.method==='POST'?'selected':''}>POST</option></select></label><label>正文格式<select name="request_format">${['form','json','text'].map(v=>`<option ${a.request_format===v?'selected':''}>${v}</option>`).join('')}</select></label></div><label>Cookie${a.has_cookie?'（已保存，留空保留）':''}<input name="cookie" type="password" autocomplete="new-password"></label><label>请求头 JSON${a.has_headers_json?'（已保存，留空保留）':''}<input name="headers_json" type="password" autocomplete="new-password" placeholder='{"Authorization":"Bearer …"}'></label><label>正文 / GET 参数${a.has_request_body?'（已保存，留空保留）':''}<textarea name="request_body" rows="3" autocomplete="off" placeholder='form/json 使用 JSON 对象，例如 {"action":"sign"}'></textarea></label><label>响应中的成功文字<input name="success_contains" required value="${esc(a.success_contains||'')}" placeholder="签到成功"></label><div class="form-row"><label>已签到文字（可空）<input name="already_contains" value="${esc(a.already_contains||'')}"></label><label>失败文字（可空）<input name="failure_contains" value="${esc(a.failure_contains||'')}"></label></div>${automationNumber('expected_status','预期 HTTP 状态',a.expected_status??200,200,299)}<p class="note">无需编写代码。HTTPS 公网站点或数字局域网地址均可配置；不跟随跳转，不执行网页脚本或验证码。凭据和正文只在 NAS 加密保存，编辑时不回显。</p>`;
if(!isBrush)fields+=`<div class="form-row"><label>随机窗口开始<input type="time" name="window_start" value="${esc(a.window_start||'08:00')}" required></label><label>随机窗口结束<input type="time" name="window_end" value="${esc(a.window_end||'10:00')}" required></label></div><p class="note">使用北京时间，同一天内结束时间须晚于开始时间。${kind==='mteam_check'?'账户检查只访问 API，不进行网页登录、签到或保号。':'修改 Cookie 后仍遵守当天执行次数限制。'}</p>`;
if(isBrush)fields+=`<label>下载器<select name="downloader_id" required><option value="">请选择下载器</option>${automationOptions(downloaders,selectedDownloader)}</select></label>${downloaders.length?'':'<p class="note">请先在设置中连接下载器。</p>'}<label>保存路径（留空使用下载器默认路径）<input name="save_path" value="${esc(a.save_path||'')}" placeholder="/downloads"></label><fieldset class="automation-fieldset"><legend>下载预算</legend><div class="automation-field-grid">${automationNumber('interval_minutes','检查间隔（分钟）',a.interval_minutes??10,2,1440)}${automationNumber('concurrent','下载器未完成任务上限',a.concurrent??8,1,100)}${automationNumber('reserve_gib','磁盘保留空间（GiB）',a.reserve_gib??100,1,1000000)}${automationNumber('capacity_gib','本任务容量上限（GiB）',a.capacity_gib??500,1,1000000)}${automationNumber('min_seeders','最少做种人数',a.min_seeders??2,2,100000)}${automationNumber('min_leechers','最少下载人数',a.min_leechers??3,3,100000)}</div><p class="note">并发包含此下载器所有未完成任务；空间预算扣除剩余下载量。只管理本任务新增的资源。</p></fieldset><fieldset class="automation-fieldset"><legend>促销筛选</legend><label class="check"><input type="checkbox" name="only_free" ${a.only_free!==false?'checked':''}>仅选择 FREE 免费资源</label><div id="automationPromotions" class="automation-promotion-options">${['FREE','_2X_FREE','NORMAL','PERCENT_50','PERCENT_70','_2X_50','_2X'].map(p=>`<label class="check"><input type="checkbox" name="promotion" value="${p}" ${(a.promotions||['FREE']).map(v=>({'50%':'PERCENT_50','70%':'PERCENT_70'})[v]||v).includes(p)?'checked':''}>${({FREE:'FREE 免费',_2X_FREE:'双倍上传免费',NORMAL:'普通（非免费）',PERCENT_50:'50% 下载',PERCENT_70:'70% 下载',_2X_50:'双倍上传 / 50% 下载',_2X:'双倍上传（非免费）','50%':'50%（兼容）','70%':'70%（兼容）'})[p]}</label>`).join('')}</div><p class="note">非 FREE 需主动选择，并且 M-Team 当前 VIP 到期时间可验证且未过期；否则只选 FREE。Torznab 仅支持免费筛选。</p></fieldset><fieldset class="automation-fieldset"><legend>观察与淘汰</legend><div class="automation-field-grid">${automationNumber('observe_hours','至少观察（小时）',a.observe_hours??6,6,8760)}${automationNumber('low_upload_kib','低上传阈值（KiB/s）',a.low_upload_kib??32,0,1000000)}</div><label class="check"><input type="checkbox" name="auto_delete" ${a.auto_delete?'checked':''}>自动移除满足条件的低速下载任务</label><p class="note">观察至少 6 小时，并取得完整一小时平均上传样本后才评估。永久保护与未满足的保种策略阻止清理。删除文件只处理有完整证明的专属目录；无共享、硬链接或多余文件时才允许，且以实际释放空间决定补种。</p>${a.id?'<button type="button" id="editAutomationProtections">管理保护名单</button>':'<p class="note">保存任务后可添加永久保护名单。</p>'}</fieldset>`;
if(isBrush)fields+=`<fieldset class="automation-fieldset"><legend>保种义务与清理文件</legend><label>新入池种子的保种规则<select name="retention_policy"><option value="unknown" ${!a.retention_policy||a.retention_policy==='unknown'?'selected':''}>未确认规则：保留不淘汰</option><option value="no_obligation" ${a.retention_policy==='no_obligation'?'selected':''}>我已确认：无额外保种义务</option><option value="seed_hours_ratio" ${a.retention_policy==='seed_hours_ratio'?'selected':''}>达到做种时间且达到分享率</option></select></label><div class="automation-field-grid">${automationNumber('min_seed_hours','最少做种小时',a.min_seed_hours??72,0,87600)}${automationNumber('min_ratio','最低分享率',a.min_ratio??1,0,10000,0.1)}${automationNumber('low_leechers','整小时下载人数阈值（0关闭）',a.low_leechers??0,0,100000)}</div><label class="check"><input type="checkbox" name="delete_data" ${a.delete_data?'checked':''}>淘汰时同时清理程序专属目录内的数据</label><p class="note">请依据自己站点的实际规则选择，软件不会代替站点作出免责判断。仅影响新添加种子，旧归属记录仍保留原保护。删除数据还需启用自动淘汰，以及 NAS 服务可读取同一下载目录；内置下载器已自动配置。</p></fieldset>`;
$('#automationDialogBody').innerHTML=`<form id="automationForm" class="form-grid">${pendingCreate?'<p class="note">有一条创建结果尚未确认。这里已恢复原设置，保存将使用同一请求编号。'+(['hdfans_signin','http_signin'].includes(kind)?' Cookie / 请求头 / 正文 不保存在浏览器中，请重新填写相同 Cookie。':'')+'</p>':''}${fields}<p id="automationModalError" class="error" role="alert"></p><div class="buttons"><button type="submit" class="primary" value="save">${a.enabled?'保存设置':'保存并保持停用'}</button>${a.enabled?'':'<button type="submit" value="enable">保存并启用</button>'}${pendingCreate?'<button type="button" id="reviewAutomationCreate">已核查原创建</button>':''}<button type="button" id="cancelAutomationEdit">取消</button></div></form>`;
const form=$('#automationForm');if(pendingCreate)$('#reviewAutomationCreate').onclick=()=>acknowledgeAutomationCreate(kind);$('#cancelAutomationEdit').onclick=closeAutomationDialog;if(isBrush){const update=()=>{const isMteam=sites.find(s=>String(s.id)===form.elements.site_id.value)?.type==='mteam';form.elements.only_free.disabled=!isMteam;if(!isMteam)form.elements.only_free.checked=true;const free=form.elements.only_free.checked;for(const checkbox of form.querySelectorAll('[name=promotion]')){checkbox.disabled=free;if(free)checkbox.checked=['FREE','_2X_FREE'].includes(checkbox.value);}};form.elements.only_free.onchange=update;form.elements.site_id.onchange=update;update();if(a.id)$('#editAutomationProtections').onclick=()=>automationProtections(a);}
form.onsubmit=async e=>{e.preventDefault();if(form.dataset.saving)return;const enabled=a.enabled===true||e.submitter?.value==='enable';let body;try{body=automationFormBody(form,a,enabled,downloaders);}catch(err){automationModalError(err.message);return;}form.dataset.saving='1';for(const button of form.querySelectorAll('[type=submit]'))button.disabled=true;try{if(a.id)await api(automationPath(a.id),'PATCH',body);else await createAutomationConfig(body);toast(enabled?'任务已保存并启用':'任务已保存，保持停用');closeAutomationDialog();await refreshAutomations();}catch(err){const uncertain=!a.id&&automationState.creates.has(kind);if(token===automationState.dialogEpoch)automationModalError(err.message+(uncertain?' 原创建回执已保留。再次保存将使用相同请求编号；请保持设置不变。':''));}finally{delete form.dataset.saving;for(const button of form.querySelectorAll('[type=submit]'))button.disabled=false;}};
}catch(e){if(token===automationState.dialogEpoch)$('#automationDialogBody').innerHTML=`<p class="error" role="alert">${esc(e.message)}</p>`;}}
function automationFormBody(form,a,enabled,downloaders=[]){const v=Object.fromEntries(new FormData(form));const body={name:v.name.trim(),enabled};if(!a.id)body.kind=a.kind;if(a.kind==='hdfans_signin'){if(v.cookie?.trim())body.cookie=v.cookie.trim();else if(!a.has_cookie)throw new Error('请填写 HDFans Cookie。');}else if(a.kind==='http_signin'){for(const key of ['signin_url','method','request_format','success_contains','already_contains','failure_contains'])body[key]=(v[key]||'').trim();body.expected_status=Number(v.expected_status);for(const key of ['cookie','headers_json','request_body'])if(v[key])body[key]=v[key];if(!body.signin_url||!body.success_contains)throw new Error('请填写签到地址和成功判定文字。');}else body.site_id=v.site_id;
if(a.kind!=='brush'){if(v.window_start>=v.window_end)throw new Error('随机窗口结束时间必须晚于开始时间。');body.window_start=v.window_start;body.window_end=v.window_end;}else{body.downloader_id=v.downloader_id;body.save_path=v.save_path.trim()||downloaders.find(d=>String(d.id)===String(v.downloader_id))?.default_save_path||'';if(!body.save_path.startsWith('/'))throw new Error('请填写下载器中的绝对保存路径，或在下载器设置中配置默认路径。');for(const key of ['interval_minutes','concurrent','reserve_gib','capacity_gib','min_seeders','min_leechers','observe_hours','low_upload_kib']){body[key]=Number(v[key]);if(!Number.isFinite(body[key]))throw new Error('请完整填写有效的数值。');}body.only_free=form.elements.only_free.checked;body.promotions=body.only_free?['FREE']:Array.from(form.querySelectorAll('[name=promotion]:checked'),c=>c.value);if(!body.promotions.length)throw new Error('请至少选择一种允许的促销类型。');body.auto_delete=form.elements.auto_delete.checked;body.delete_data=!!form.elements.delete_data?.checked;body.retention_policy=v.retention_policy||"unknown";body.min_seed_hours=Number(v.min_seed_hours??72);body.min_ratio=Number(v.min_ratio??1);body.low_leechers=Number(v.low_leechers??0);if(body.delete_data&&!body.auto_delete)throw new Error("清理数据需要同时开启自动淘汰。");}return body;}
async function toggleAutomation(a,button){const id=String(a.id);if(automationState.busy.has(id))return;automationState.busy.add(id);button.disabled=true;try{await api(automationPath(id),'PATCH',{enabled:!a.enabled});toast(a.enabled?'定时任务已停用；正在运行的任务可使用“停止并停用”结束':'任务已启用');await refreshAutomations();}catch(e){toast(e.message);}finally{automationState.busy.delete(id);button.disabled=false;renderAutomations();}}
function automationRunDialog(a,preview=false){automationDialog(preview?'预演任务':'执行任务',`<h3>${esc(a.name)}</h3><p class="note">预演只检查规则并说明计划，不签到、不添加或移除下载任务。</p>${!a.enabled?'<p class="note">任务当前停用。真实执行需要先启用，可在列表开关或编辑时启用。</p>':''}<p class="note">${a.kind==='mteam_check'?'真实执行只做账户 API 检查，非网页登录保号。':['hdfans_signin','http_signin'].includes(a.kind)?'真实执行会向配置的站点发送签到请求，当天结果不明时请人工核查。':'真实执行可能新增下载；开启自动移除时，仅处理有归属证据且无保护义务的任务。'}</p><p id="automationModalError" class="error" role="alert"></p><div class="buttons"><button id="previewAutomationRun" class="primary">开始预演</button>${preview?'':`<button id="realAutomationRun" ${a.enabled?'':'disabled'}>确认真实执行</button>`}<button id="cancelAutomationRun">取消</button></div>`);$('#previewAutomationRun').onclick=e=>submitAutomationRun(a,true,e.target);const real=$('#realAutomationRun');if(real)real.onclick=e=>submitAutomationRun(a,false,e.target);$('#cancelAutomationRun').onclick=closeAutomationDialog;}
async function submitAutomationRun(a,dryRun,button){
 const key=JSON.stringify([String(a.id),dryRun]),lock='run:'+key;if(automationState.busy.has(lock))return;
 const existing=automationState.pending.get(key);if(existing){showAutomationRun(existing,key,a.name);return;}
 automationState.busy.add(lock);button.disabled=true;const token=automationState.dialogEpoch,scope=automationState.scope;
 const receipt={automation_id:String(a.id),dry_run:dryRun,request_id:uuid(),run_id:null};automationState.pending.set(key,receipt);
 try{try{saveAutomationPending();}catch(e){automationState.pending.delete(key);throw e;}
  const data=await api(automationPath(a.id)+'/run','POST',{dry_run:receipt.dry_run,request_id:receipt.request_id});
  if(scope!==automationState.scope)return;receipt.run_id=data.run_id;try{saveAutomationPending();}catch(e){throw new Error('执行已提交，但运行回执未能更新。原请求编号已保留，再次点击将确认同一次运行。');}
  if(token===automationState.dialogEpoch&&automationState.active)showAutomationRun(receipt,key,a.name);
 }catch(e){
  if(e.httpStatus&&e.httpStatus<500&&e.httpStatus!==409){try{removeAutomationPending(key);}catch(cleanup){toast(cleanup.message);}}
  if(token===automationState.dialogEpoch&&automationState.active){if(automationState.pending.has(key)){showAutomationRun(receipt,key,a.name);automationModalError('请求结果尚未确认，正在查询原请求。'+e.message);}else automationModalError(e.message);}
 }finally{automationState.busy.delete(lock);button.disabled=false;}
}
function showAutomationRun(receipt,key,name){const token=automationDialog(receipt.dry_run?'预演回执':'执行回执',`<h3>${esc(name||'自动化任务')}</h3><p class="note">${receipt.dry_run?'只读预演':'真实执行'} · 关闭窗口不会取消已登记的 NAS 执行。</p><p id="automationRunStatus" role="status">正在查询运行状态…</p><div id="automationRunResult"></div><div id="automationRunRecovery"></div><p class="note automation-receipt">回执：${esc(receipt.request_id)}</p><p id="automationModalError" class="error" role="alert"></p><div class="buttons"><button id="checkAutomationRun">刷新状态</button><button id="closeAutomationRun">关闭</button></div>`);$('#checkAutomationRun').onclick=()=>pollAutomationRun(receipt,key,token);$('#closeAutomationRun').onclick=closeAutomationDialog;pollAutomationRun(receipt,key,token);}
function acknowledgeAutomationRun(receipt,key){
 if(automationState.pending.get(key)?.request_id!==receipt.request_id)return;
 try{removeAutomationPending(key);closeAutomationDialog();toast('本地回执已关闭；后端未确认操作、每日次数和资源保护继续保留。');}catch(e){automationModalError(e.message);}
}
async function retryMissingAutomationRun(receipt,key,token,button){
 const lock='run:'+key;if(automationState.busy.has(lock)||token!==automationState.dialogEpoch)return;automationState.busy.add(lock);button.disabled=true;
 try{const data=await api(automationPath(receipt.automation_id)+'/run','POST',{request_id:receipt.request_id,dry_run:receipt.dry_run});receipt.run_id=data.run_id;saveAutomationPending();if(token===automationState.dialogEpoch)await pollAutomationRun(receipt,key,token);}
 catch(e){if(token===automationState.dialogEpoch)automationModalError(e.message+' 原请求编号保留，可刷新状态后核查。');}
 finally{automationState.busy.delete(lock);button.disabled=false;}
}
async function pollAutomationRun(receipt,key,token){
 if(token!==automationState.dialogEpoch||!$('#automationDialog').open||!automationState.active)return;clearTimeout(automationState.runTimer);
 try{const data=await api('/automation-runs/'+encodeURIComponent(receipt.run_id||receipt.request_id));
  if(token!==automationState.dialogEpoch||!$('#automationDialog').open||!automationState.active)return;const run=data.item;
  $('#automationRunStatus').textContent=automationStatus(run.status);$('#automationRunResult').innerHTML=automationResult(run.result);$('#automationRunRecovery').innerHTML='';automationModalError('');
  if(automationFinished(run.status)){if(automationState.pending.get(key)?.request_id===receipt.request_id)removeAutomationPending(key);await refreshAutomations();}
  else if(['needs_review','interrupted'].includes(run.status)){
   $('#automationRunRecovery').innerHTML='<p class="note">请先核查站点或下载器实际结果。确认后可关闭本地回执，再次运行会重新检查后端保护，不会解除未确认操作或保种义务。</p><button id="ackAutomationRun">已核查，关闭本地回执</button>';
   $('#ackAutomationRun').onclick=()=>acknowledgeAutomationRun(receipt,key);
  }else if(['queued','running'].includes(run.status))automationState.runTimer=setTimeout(()=>pollAutomationRun(receipt,key,token),2000);
 }catch(e){if(token!==automationState.dialogEpoch)return;
  if(e.httpStatus===404){$('#automationRunStatus').textContent='尚未找到这次运行';$('#automationRunRecovery').innerHTML='<p class="note">NAS 尚未登记此请求。确认继续时使用原请求编号提交，避免生成重复运行。</p><button id="retryMissingAutomationRun">确认使用原编号重新提交</button>';$('#retryMissingAutomationRun').onclick=event=>retryMissingAutomationRun(receipt,key,token,event.target);automationModalError('');}
  else automationModalError(e.message+' 可稍后刷新原回执。');
 }
}
const automationResultLabels={effective_promotions:'本次允许促销',reconciled_operations:'已确认的历史操作',needs_review:'需要人工核查',message:'说明',reason:'原因',would_add:'拟新增的资源编号',added:'已添加资源',removed:'已移除任务',deleted:'已移除任务',status:'结果',vip:'VIP 状态',vip_until:'VIP 到期时间',vip_expiry:'VIP 到期时间',candidates:'候选资源',free_gib:'可用空间（GiB）',dry_run:'只读预演',skipped:'跳过',protected:'保护资源',actions:'动作',checked:'已检查',username:'账户',downloaded:'下载量',uploaded:'上传量',ratio:'分享率',would_delete:'拟移除任务',would_remove:'拟移除任务',next_run:'下次执行'};
const automationReasons={disk_or_capacity_limit:'磁盘保留空间或任务容量不足',no_eligible_candidates:'暂无满足全部规则的候选资源',uncertain_operation:'存在未确认操作，需人工核查',uncertain_add:'新增下载结果待核查',vip_expired:'VIP 已到期，非免费候选被跳过',preview:'只读预演完成',added:'已新增下载任务',identity_changed:'任务标记或身份已变更，保留',permanent_protection:'永久保护，保留',obligations_unknown:'保种义务未知，保留',observation_window:'尚在观察期，保留',incomplete:'下载未完成，保留',insufficient_hour_samples:'不足一小时上传样本，保留',uploading_effectively:'平均上传达到阈值，保留',low_upload:'上传低于阈值',service_restarted:'服务重启中断，已登记操作不会重放',concurrency_limit:'下载器未完成任务已达到上限',capacity_limit:'已达到本任务容量上限',disk_reserve:'未达到磁盘保留空间要求',no_candidates:'暂无符合规则的候选资源',already_exists:'下载器已有此资源',protected:'资源受到保护',unknown_obligation:'站点保种义务尚未确认',daily_limit:'今天已有签到尝试，不重复提交',stopped:'任务已停止',disabled:'任务未启用'};
function automationSafeText(value){return String(value??'').replace(/https?:\/\/[^\s<>"']+/gi,'[链接已隐藏]').replace(/((?:cookie|passkey|api[_ -]?key|authorization)\s*[:=]\s*)[^\s,;]+/gi,'$1[已隐藏]');}
function automationResult(result){if(!result||typeof result!=='object')return result?`<p class="note">${esc(automationSafeText(result))}</p>`:'';const retention=Array.isArray(result.retention)&&result.retention.length?'<div class="automation-retention"><h3>资源保留评估</h3>'+result.retention.map(i=>'<div class="item"><code class="automation-hash">'+esc(i.info_hash)+'</code><p>'+esc(automationReasons[i.reason]||automationSafeText(i.reason))+(i.needs_review?' · 结果待核查':i.would_delete?' · 满足移除评估条件':'')+'</p></div>').join('')+'</div>':'';const rows=Object.entries(result).filter(([key])=>Object.hasOwn(automationResultLabels,key));return retention+rows.map(([key,value])=>{let text;if(key==='reason')text=automationReasons[value]||automationSafeText(value);else if((key==='vip_until'||key==='vip_expiry'||key==='next_run')&&typeof value==='number')text=automationDate(value);else if(key==='status')text=automationStatus(value);else if(typeof value==='boolean')text=value?'是':'否';else if(key==='effective_promotions'&&Array.isArray(value))text=value.map(v=>({FREE:'免费',_2X_FREE:'双倍上传免费',NORMAL:'普通',PERCENT_50:'50% 下载',PERCENT_70:'70% 下载',_2X_50:'双倍上传 / 50% 下载',_2X:'双倍上传'})[v]||automationSafeText(v)).join('、');else if(Array.isArray(value))text=value.map(v=>typeof v==='object'?'详情已记录':automationSafeText(v)).join('、')||'无';else if(value&&typeof value==='object')text='详情已记录';else text=automationSafeText(value);return `<div class="detail-line"><span>${esc(automationResultLabels[key])}</span><span>${esc(text)}</span></div>`;}).join('')||'<p class="note">没有可显示的结果明细。</p>';}
async function stopAutomation(a,button){const id=String(a.id);if(automationState.busy.has(id))return;automationState.busy.add(id);button.disabled=true;try{await api(automationPath(id)+'/stop','POST',{});toast('已停止并停用；已发出的请求可能仍在确认，请查看日志。');await refreshAutomations();}catch(e){toast(e.message);}finally{automationState.busy.delete(id);button.disabled=false;renderAutomations();}}
function deleteAutomation(a){automationDialog('删除自动化配置',`<p>删除「${esc(a.name)}」的自动化配置？</p><p class="note">将停用并移除这条配置，保留审计记录。不删除下载器中的下载任务，也不删除已下载文件。</p><p id="automationModalError" class="error" role="alert"></p><div class="buttons"><button id="confirmDeleteAutomation" class="danger">删除配置</button><button id="cancelDeleteAutomation">取消</button></div>`);$('#cancelDeleteAutomation').onclick=closeAutomationDialog;$('#confirmDeleteAutomation').onclick=async e=>{e.target.disabled=true;try{await api(automationPath(a.id),'DELETE');toast('自动化配置已删除，下载任务和文件保留');closeAutomationDialog();await refreshAutomations();}catch(err){automationModalError(err.message);e.target.disabled=false;}};}
async function automationLogs(a){const token=automationDialog('执行日志 · '+a.name,'<p class="note">正在读取最近运行…</p>');try{const data=await api(automationPath(a.id)+'/logs?limit=50');if(token!==automationState.dialogEpoch)return;$('#automationDialogBody').innerHTML=`<p class="note">最近 ${data.items.length} 次运行。预演与真实执行分开标记；“已完成”请结合结果说明查看。</p>${data.items.map(run=>`<article class="automation-log"><div class="automation-log-title"><strong>${esc(automationStatus(run.status))}</strong><span>${run.dry_run?'预演':'真实执行'}</span></div><p class="note">${esc(automationDate(run.created_at||run.started_at))}${run.finished_at?' · 结束 '+esc(automationDate(run.finished_at)):''}</p>${automationResult(run.result)}</article>`).join('')||'<div class="empty"><h3>暂无执行日志</h3><p>保存任务后，可先预演检查配置。</p></div>'}`;}catch(e){if(token===automationState.dialogEpoch)$('#automationDialogBody').innerHTML=`<p class="error">${esc(e.message)}</p>`;}}
async function automationProtections(a){const token=automationDialog('保护名单 · '+a.name,'<p class="note">正在读取保护名单…</p>');try{const [list,owned]=await Promise.all([api(automationPath(a.id)+'/protections'),api(automationPath(a.id)+'/owned')]);if(token!==automationState.dialogEpoch)return;$('#automationDialogBody').innerHTML=`<p class="note">永久保护的资源不会自动移除。取消此保护后，HR、保种义务等其他保护仍然有效。</p><form id="automationProtectionForm" class="form-grid"><label>资源信息哈希<input name="info_hash" required pattern="[a-fA-F0-9]{40}" maxlength="40" placeholder="40 位资源信息哈希" autocomplete="off"></label><label>保护原因<input name="reason" maxlength="160" value="长期保种"></label><button type="submit" class="primary">加入永久保护</button></form><p id="automationModalError" class="error" role="alert"></p><div class="detail-section"><h3>永久保护（${list.items.length}）</h3>${list.items.map(i=>`<div class="item"><code class="automation-hash">${esc(i.info_hash)}</code><p>${esc(i.reason||'永久保护')}</p><div class="buttons"><button data-auto-unprotect="${esc(i.info_hash)}">取消永久保护</button></div></div>`).join('')||'<p class="note">尚未添加永久保护。</p>'}</div><div class="detail-section"><h3>本任务管理的资源（${owned.items.length}）</h3>${owned.items.map(i=>`<div class="item"><h3>${esc(i.name||i.title||('资源 '+String(i.info_hash||'').slice(0,12)))}</h3><code class="automation-hash">${esc(i.info_hash)}</code><p>${esc(automationStatus(i.state||i.status))}</p><div class="buttons"><button data-auto-protect="${esc(i.info_hash)}">保护此资源</button></div></div>`).join('')||'<p class="note">暂无有归属证据的资源。已有下载不会被接管。</p>'}</div>`;
$('#automationProtectionForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;try{const v=Object.fromEntries(new FormData(e.target));await api(automationPath(a.id)+'/protections','POST',{info_hash:v.info_hash.trim().toLowerCase(),reason:v.reason.trim()});await automationProtections(a);}catch(err){automationModalError(err.message);button.disabled=false;}};
$('#automationDialogBody').onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.autoProtect){$('#automationProtectionForm').elements.info_hash.value=b.dataset.autoProtect;$('#automationProtectionForm').elements.reason.focus();}if(b.dataset.autoUnprotect){b.disabled=true;try{await api(automationPath(a.id)+'/protections/'+encodeURIComponent(b.dataset.autoUnprotect),'DELETE');await automationProtections(a);}catch(err){automationModalError(err.message);b.disabled=false;}}};
}catch(e){if(token===automationState.dialogEpoch)$('#automationDialogBody').innerHTML=`<p class="error">${esc(e.message)}</p>`;}}
$('#viewAutomations').onclick=openAutomations;
$('#newAutomation').onclick=newAutomation;
$('#refreshAutomations').onclick=()=>refreshAutomations();
$('#closeAutomationDialog').onclick=closeAutomationDialog;
$('#automationDialog').addEventListener('cancel',closeAutomationDialog);
$('#automationDialog').addEventListener('close',()=>{++automationState.dialogEpoch;clearTimeout(automationState.runTimer);});
$('#automationTabs').onclick=e=>{const b=e.target.closest('[data-auto-filter]');if(!b)return;automationState.filter=b.dataset.autoFilter;for(const tab of $('#automationTabs').children){const active=tab===b;tab.classList.toggle('active',active);tab.setAttribute('aria-pressed',String(active));}renderAutomations();};
$('#automationList').onclick=e=>{const b=e.target.closest('[data-auto-action]');if(!b)return;const a=automationState.items.find(item=>String(item.id)===b.dataset.autoId);if(!a)return;const actions={edit:()=>automationForm(a),preview:()=>automationRunDialog(a,true),run:()=>automationRunDialog(a),toggle:()=>toggleAutomation(a,b),stop:()=>stopAutomation(a,b),logs:()=>automationLogs(a),delete:()=>deleteAutomation(a),protections:()=>automationProtections(a)};actions[b.dataset.autoAction]?.();};
$('#automationDialogBody').addEventListener('click',e=>{const b=e.target.closest('[data-auto-kind]');if(b)automationForm({kind:b.dataset.autoKind,enabled:false});});
